package ilcg;
import java.io.*;
import java.util.*;
/** class to update versions*/

public class Ver
{
    public static void main(String []args)
    {
        try
            {
                String root=args[0];
                float version;
                if(root =="")throw new Exception("no file name parameter provide");
                String pack=args[1];
                if(pack=="") throw new Exception("no package parameter provided");
                String path= pack.replace('.','/');
                FileInputStream sf;
                try
                    {
                        sf = new FileInputStream(path+"/"+root + ".ver");
                    }
                catch(FileNotFoundException fnf)
                    {
                        FileOutputStream fo= new FileOutputStream(path+"/"+root+".ver");
                        DataOutputStream dao= new DataOutputStream(fo);
                        dao.writeFloat(0);
                        dao.flush();
                        fo.close();
                        sf=new FileInputStream(path+"/"+root+".ver");
                        if(!sf.getFD().valid())throw new Exception("can not create "+root+".ver");
                    }
                DataInputStream di=new DataInputStream(sf);
                version=di.readFloat();
                version+=0.000578;
                System.out.println("new version "+version);
                sf.close();
                FileOutputStream fo= new FileOutputStream(path+"/"+root+".ver");
                DataOutputStream dao= new DataOutputStream(fo);
                dao.writeFloat(version);
                dao.flush();
                fo.close();
                fo=new FileOutputStream(path+"/"+root+"Ver.java");
                PrintStream ps = new PrintStream(fo);
                ps.println("package "+pack+";/* file generated by ilcg.Ver.java */");
                ps.println("/** Version management class*/");
                ps.print("public class "+root+"Ver{");
                ps.println("public static double VERSION="+version+";}");
                ps.flush();
                ps.close();
            }
        catch(Exception en)
            {
                System.out.println(en);
                System.out.println("Usage : java ilcg.Ver <sourcename> <packagename>");
                System.out.println("sourcename must not include .java");
                System.out.println("package name is a valid java package name");
            }
    }
}
