SECTION .text ; procedure generated by code generator IA32CG
	global _main
_main: enter  spacefor_main,0
 mov ebx,DWORD  [ ebp+-84]
 cmp ebx, 4
 setl BYTE  [ ebp+-301]
spacefor_main equ 301
 leave
 ret
