%ifndef vq8
%define vq8 ; defined by walker;0
section .text  ;0
; procedure generated by code generator class ilcg.tree.PentiumCG;0
labelff6b1cf7d910:;0
;	 encode;0
; entering a procedure at lexical level 1;0
 enter   0,1;0
 sub esp,spaceforencodel0;0
; #29;0
 mov DWORD  [  ebp+     -536],     0;0
 labelff6b1cf8fc20:;0
  cmp DWORD  [  ebp+     -536],      63;0
 jg near  labelff6b1cf8fc22;0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     -536];0
 mov esi,DWORD  [  ebp+     8];0
 movsx esi,BYTE    [  esi+eax];0
 mov dword[fttemp], esi;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  ebp+ eax* 4+     -512];2
 inc DWORD  [  ebp+     -536];0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     -536];0
 mov esi,DWORD  [  ebp+     8];0
 movsx esi,BYTE    [  esi+eax];0
 mov dword[fttemp], esi;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  ebp+ eax* 4+     -512];2
 inc DWORD  [  ebp+     -536];0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     -536];0
 mov esi,DWORD  [  ebp+     8];0
 movsx esi,BYTE    [  esi+eax];0
 mov dword[fttemp], esi;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  ebp+ eax* 4+     -512];2
 inc DWORD  [  ebp+     -536];0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     -536];0
 mov esi,DWORD  [  ebp+     8];0
 movsx esi,BYTE    [  esi+eax];0
 mov dword[fttemp], esi;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  ebp+ eax* 4+     -512];2
 inc DWORD  [  ebp+     -536];0
 jmp  labelff6b1cf8fc20;0
 labelff6b1cf8fc22:;0
; #30;0
 mov DWORD  [  ebp+     -528],     0;0
; #30;0
 floadlit 128.0;2
 fstp dword  [  ebp+     -520];2
; #39;0
 mov bx,WORD  [   labelff6b1cf1d38+     -81940];0
 movsx edi,   bx;0
 lea edi,[  edi+     -1];0
 mov DWORD  [  ebp+     -544],edi;0
 mov DWORD  [  ebp+     -524],     0;0
 labelff6b1cfb1924:;0
 mov edi,DWORD  [  ebp+     -524];0
 cmp edi,dword    [  ebp+     -544];0
 jg near  labelff6b1cfb1926;0
; #33;0
 floadlit 0.0;2
 fstp dword  [  ebp+     -552];2
 mov DWORD  [  ebp+     -548],     63;0
 labelff6b1cfb2328:;0
  cmp DWORD  [  ebp+     -548],      0;0
 jl near  labelff6b1cfb232a;0
 mov esi,DWORD  [  ebp+     -548];0
 fld dword  [  ebp+ esi* 4+     -512];2
 imul esi,DWORD  [  ebp+     -524],    256;0
 mov ebx,DWORD  [  ebp+     -548];0
 fsub DWORD  [  esi+ ebx* 4+  labelff6b1cf1d38+     -65536];2
 mov esi,DWORD  [  ebp+     -548];0
 fld dword  [  ebp+ esi* 4+     -512];2
 imul esi,DWORD  [  ebp+     -524],    256;0
 mov ebx,DWORD  [  ebp+     -548];0
 fsub DWORD  [  esi+ ebx* 4+  labelff6b1cf1d38+     -65536];2
 fmulp st1;2
 fadd DWORD  [  ebp+     -552];2
 fstp dword  [  ebp+     -552];2
 add  DWORD  [  ebp+     -548],     -1;0
 mov esi,DWORD  [  ebp+     -548];0
 fld dword  [  ebp+ esi* 4+     -512];2
 imul esi,DWORD  [  ebp+     -524],    256;0
 mov ebx,DWORD  [  ebp+     -548];0
 fsub DWORD  [  esi+ ebx* 4+  labelff6b1cf1d38+     -65536];2
 mov esi,DWORD  [  ebp+     -548];0
 fld dword  [  ebp+ esi* 4+     -512];2
 imul esi,DWORD  [  ebp+     -524],    256;0
 mov ebx,DWORD  [  ebp+     -548];0
 fsub DWORD  [  esi+ ebx* 4+  labelff6b1cf1d38+     -65536];2
 fmulp st1;2
 fadd DWORD  [  ebp+     -552];2
 fstp dword  [  ebp+     -552];2
 add  DWORD  [  ebp+     -548],     -1;0
 mov esi,DWORD  [  ebp+     -548];0
 fld dword  [  ebp+ esi* 4+     -512];2
 imul esi,DWORD  [  ebp+     -524],    256;0
 mov ebx,DWORD  [  ebp+     -548];0
 fsub DWORD  [  esi+ ebx* 4+  labelff6b1cf1d38+     -65536];2
 mov esi,DWORD  [  ebp+     -548];0
 fld dword  [  ebp+ esi* 4+     -512];2
 imul esi,DWORD  [  ebp+     -524],    256;0
 mov ebx,DWORD  [  ebp+     -548];0
 fsub DWORD  [  esi+ ebx* 4+  labelff6b1cf1d38+     -65536];2
 fmulp st1;2
 fadd DWORD  [  ebp+     -552];2
 fstp dword  [  ebp+     -552];2
 add  DWORD  [  ebp+     -548],     -1;0
 mov esi,DWORD  [  ebp+     -548];0
 fld dword  [  ebp+ esi* 4+     -512];2
 imul esi,DWORD  [  ebp+     -524],    256;0
 mov ebx,DWORD  [  ebp+     -548];0
 fsub DWORD  [  esi+ ebx* 4+  labelff6b1cf1d38+     -65536];2
 mov esi,DWORD  [  ebp+     -548];0
 fld dword  [  ebp+ esi* 4+     -512];2
 imul esi,DWORD  [  ebp+     -524],    256;0
 mov ebx,DWORD  [  ebp+     -548];0
 fsub DWORD  [  esi+ ebx* 4+  labelff6b1cf1d38+     -65536];2
 fmulp st1;2
 fadd DWORD  [  ebp+     -552];2
 fstp dword  [  ebp+     -552];2
 add  DWORD  [  ebp+     -548],     -1;0
 jmp  labelff6b1cfb2328;0
 labelff6b1cfb232a:;0
 fld dword  [  ebp+     -552];2
 fstp dword  [  ebp+     -556];2
 fld dword  [  ebp+     -556];2
 fstp dword  [  ebp+     -516];2
; #39;0
 fld dword  [  ebp+     -516];2
 fcomp dword  [  ebp+     -520] ;2
push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb near  labelff6b1cfc8b2c;0
 jmp  labelff6b1cfc8b2e;0
 labelff6b1cfc8b2c:;0
; #36;0
 mov edi,DWORD  [  ebp+     -524];0
 mov DWORD  [  ebp+     -528],edi;0
; #37;0
 fld dword  [  ebp+     -516];2
 fstp dword  [  ebp+     -520];2
; #38;0
 labelff6b1cfc8b2e:;0
 inc DWORD  [  ebp+     -524];0
 jmp  labelff6b1cfb1924;0
 labelff6b1cfb1926:;0
; #40;0
 mov eax,DWORD  [  ebp+     -528];0
 mov BYTE  [  ebp+     -5],al;0
; #41;0
 labelff6b1cf7d91a:;0
 movzx eax, BYTE   [  ebp+     -5];0
spaceforencodel0 equ 556;0
encodel0exit:;0
leave;0
 ret 0;4
section .text  ;0
; procedure generated by code generator class ilcg.tree.PentiumCG;0
labelff6b1cf8ca1c:;0
;	 unit$vq8;0
; entering a unit at lexical level 0;0
unit$vq8:;0
 enter  0,0;0
 call unit$system;4
cmp byte[unit$vq8ready],1;0
 jnz unit$vq8init;0
 jmp unit$vq8l1exit;0
unit$vq8init:mov byte[unit$vq8ready],1;0
; #43;0
 mov WORD  [   labelff6b1cf1d38+     -81940],   256;0
; #44;0
 mov WORD  [   labelff6b1cf1d38+     -81938],   65;0
; #45;0
 mov DWORD  [   labelff6b1cf1d38+     -81944],     0;0
 labelff6b1cfcd130:;0
  cmp DWORD  [   labelff6b1cf1d38+     -81944],      255;0
 jg near  labelff6b1cfcd132;0
 mov DWORD  [   labelff6b1cf1d38+     -81948],     0;0
 labelff6b1cfcd134:;0
  cmp DWORD  [   labelff6b1cf1d38+     -81948],      63;0
 jg near  labelff6b1cfcd136;0
 imul esi,DWORD  [   labelff6b1cf1d38+     -81944],    64;0
 mov ebx,DWORD  [   labelff6b1cf1d38+     -81948];0
 fild DWORD  [   labelff6b1cf1d38+     -81944];2
 floadlit 129.0;2
 fdivp st1;2
 floadlit -1.0;2
 faddp st1;2
 floadlit -1.0;2
 fcom st0,st1  ;2
push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jnb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 1.0;2
 fcom st0,st1  ;2
 push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 127.5;2
 fmulp st1;2
 floadlit -0.5;2
 faddp st1;2
  frndint;2
 sub esp,4;0
 fistp dword [esp];2
 pop  eax;0
 mov dword[fttemp], eax;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 pop  edx;0
 mov BYTE  [  esi+ebx +  labelff6b1cf1d38+     -81936],dl;0
 inc DWORD  [   labelff6b1cf1d38+     -81948];0
 imul esi,DWORD  [   labelff6b1cf1d38+     -81944],    64;0
 mov ebx,DWORD  [   labelff6b1cf1d38+     -81948];0
 fild DWORD  [   labelff6b1cf1d38+     -81944];2
 floadlit 129.0;2
 fdivp st1;2
 floadlit -1.0;2
 faddp st1;2
 floadlit -1.0;2
 fcom st0,st1  ;2
push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jnb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 1.0;2
 fcom st0,st1  ;2
 push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 127.5;2
 fmulp st1;2
 floadlit -0.5;2
 faddp st1;2
  frndint;2
 sub esp,4;0
 fistp dword [esp];2
 pop  edx;0
 mov BYTE  [  esi+ebx +  labelff6b1cf1d38+     -81936],dl;0
 inc DWORD  [   labelff6b1cf1d38+     -81948];0
 imul esi,DWORD  [   labelff6b1cf1d38+     -81944],    64;0
 mov ebx,DWORD  [   labelff6b1cf1d38+     -81948];0
 fild DWORD  [   labelff6b1cf1d38+     -81944];2
 floadlit 129.0;2
 fdivp st1;2
 floadlit -1.0;2
 faddp st1;2
 floadlit -1.0;2
 fcom st0,st1  ;2
push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jnb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 1.0;2
 fcom st0,st1  ;2
 push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 127.5;2
 fmulp st1;2
 floadlit -0.5;2
 faddp st1;2
  frndint;2
 sub esp,4;0
 fistp dword [esp];2
 pop  edx;0
 mov BYTE  [  esi+ebx +  labelff6b1cf1d38+     -81936],dl;0
 inc DWORD  [   labelff6b1cf1d38+     -81948];0
 imul esi,DWORD  [   labelff6b1cf1d38+     -81944],    64;0
 mov ebx,DWORD  [   labelff6b1cf1d38+     -81948];0
 fild DWORD  [   labelff6b1cf1d38+     -81944];2
 floadlit 129.0;2
 fdivp st1;2
 floadlit -1.0;2
 faddp st1;2
 floadlit -1.0;2
 fcom st0,st1  ;2
push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jnb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 1.0;2
 fcom st0,st1  ;2
 push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 127.5;2
 fmulp st1;2
 floadlit -0.5;2
 faddp st1;2
  frndint;2
 sub esp,4;0
 fistp dword [esp];2
 pop  edx;0
 mov BYTE  [  esi+ebx +  labelff6b1cf1d38+     -81936],dl;0
 inc DWORD  [   labelff6b1cf1d38+     -81948];0
 jmp  labelff6b1cfcd134;0
 labelff6b1cfcd136:;0
 inc DWORD  [   labelff6b1cf1d38+     -81944];0
 jmp  labelff6b1cfcd130;0
 labelff6b1cfcd132:;0
; #47;0
 mov DWORD  [   labelff6b1cf1d38+     -81960],     0;0
 labelff6b1d02cd38:;0
  cmp DWORD  [   labelff6b1cf1d38+     -81960],      255;0
 jg near  labelff6b1d02cd3a;0
 mov DWORD  [   labelff6b1cf1d38+     -81964],     0;0
 labelff6b1d02d73c:;0
  cmp DWORD  [   labelff6b1cf1d38+     -81964],      63;0
 jg near  labelff6b1d02d73e;0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [   labelff6b1cf1d38+     -81964];0
 imul esi,DWORD  [   labelff6b1cf1d38+     -81960],    256;0
 imul ebx,DWORD  [   labelff6b1cf1d38+     -81960],    64;0
 movsx ebx,BYTE    [  ebx+eax +  labelff6b1cf1d38+     -81936];0
 mov dword[fttemp], ebx;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  esi+ eax* 4+  labelff6b1cf1d38+     -65536];2
 inc DWORD  [   labelff6b1cf1d38+     -81964];0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [   labelff6b1cf1d38+     -81964];0
 imul esi,DWORD  [   labelff6b1cf1d38+     -81960],    256;0
 imul ebx,DWORD  [   labelff6b1cf1d38+     -81960],    64;0
 movsx ebx,BYTE    [  ebx+eax +  labelff6b1cf1d38+     -81936];0
 mov dword[fttemp], ebx;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  esi+ eax* 4+  labelff6b1cf1d38+     -65536];2
 inc DWORD  [   labelff6b1cf1d38+     -81964];0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [   labelff6b1cf1d38+     -81964];0
 imul esi,DWORD  [   labelff6b1cf1d38+     -81960],    256;0
 imul ebx,DWORD  [   labelff6b1cf1d38+     -81960],    64;0
 movsx ebx,BYTE    [  ebx+eax +  labelff6b1cf1d38+     -81936];0
 mov dword[fttemp], ebx;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  esi+ eax* 4+  labelff6b1cf1d38+     -65536];2
 inc DWORD  [   labelff6b1cf1d38+     -81964];0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [   labelff6b1cf1d38+     -81964];0
 imul esi,DWORD  [   labelff6b1cf1d38+     -81960],    256;0
 imul ebx,DWORD  [   labelff6b1cf1d38+     -81960],    64;0
 movsx ebx,BYTE    [  ebx+eax +  labelff6b1cf1d38+     -81936];0
 mov dword[fttemp], ebx;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  esi+ eax* 4+  labelff6b1cf1d38+     -65536];2
 inc DWORD  [   labelff6b1cf1d38+     -81964];0
 jmp  labelff6b1d02d73c;0
 labelff6b1d02d73e:;0
 inc DWORD  [   labelff6b1cf1d38+     -81960];0
 jmp  labelff6b1d02cd38;0
 labelff6b1d02cd3a:;0
; #48;0
 labelff6b1cf7d912:;0
spaceforunit$vq8l1 equ 81972;0
unit$vq8l1exit:;0
leave;0
 ret 0;4
	SECTION .bss;0
	alignb 16;0
resb spaceforunit$vq8l1;0
	alignb 16;0
 labelff6b1cf1d38:;0
	SECTION .data;0
unit$vq8ready dd 0;0
%include "c:\src\VectorPascal\mmpc/system.asm"
%endif
