/* This file was generated by SableCC (http://www.sablecc.org/). */

package ilcgasm.analysis;

import java.util.*;
import ilcgasm.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable in;
    private Hashtable out;

    public Object getIn(Node node)
    {
        if(in == null)
        {
            return null;
        }

        return in.get(node);
    }

    public void setIn(Node node, Object in)
    {
        if(this.in == null)
        {
            this.in = new Hashtable(1);
        }

        if(in != null)
        {
            this.in.put(node, in);
        }
        else
        {
            this.in.remove(node);
        }
    }

    public Object getOut(Node node)
    {
        if(out == null)
        {
            return null;
        }

        return out.get(node);
    }

    public void setOut(Node node, Object out)
    {
        if(this.out == null)
        {
            this.out = new Hashtable(1);
        }

        if(out != null)
        {
            this.out.put(node, out);
        }
        else
        {
            this.out.remove(node);
        }
    }
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    public void caseAProgram(AProgram node)
    {
        defaultCase(node);
    }

    public void caseAReference(AReference node)
    {
        defaultCase(node);
    }

    public void caseAArray(AArray node)
    {
        defaultCase(node);
    }

    public void caseAIdentifierId(AIdentifierId node)
    {
        defaultCase(node);
    }

    public void caseAOpId(AOpId node)
    {
        defaultCase(node);
    }

    public void caseATypeidTypes(ATypeidTypes node)
    {
        defaultCase(node);
    }

    public void caseAArrayTypes(AArrayTypes node)
    {
        defaultCase(node);
    }

    public void caseACartesianTypes(ACartesianTypes node)
    {
        defaultCase(node);
    }

    public void caseAReftypeTypes(AReftypeTypes node)
    {
        defaultCase(node);
    }

    public void caseAType(AType node)
    {
        defaultCase(node);
    }

    public void caseANullParams(ANullParams node)
    {
        defaultCase(node);
    }

    public void caseAListParams(AListParams node)
    {
        defaultCase(node);
    }

    public void caseATypetail(ATypetail node)
    {
        defaultCase(node);
    }

    public void caseACartval(ACartval node)
    {
        defaultCase(node);
    }

    public void caseACarttail(ACarttail node)
    {
        defaultCase(node);
    }

    public void caseALow(ALow node)
    {
        defaultCase(node);
    }

    public void caseAHigh(AHigh node)
    {
        defaultCase(node);
    }

    public void caseARealValue(ARealValue node)
    {
        defaultCase(node);
    }

    public void caseAIntValue(AIntValue node)
    {
        defaultCase(node);
    }

    public void caseATypeValue(ATypeValue node)
    {
        defaultCase(node);
    }

    public void caseAIdValue(AIdValue node)
    {
        defaultCase(node);
    }

    public void caseAStringValue(AStringValue node)
    {
        defaultCase(node);
    }

    public void caseACastValue(ACastValue node)
    {
        defaultCase(node);
    }

    public void caseAFnValue(AFnValue node)
    {
        defaultCase(node);
    }

    public void caseAProcValue(AProcValue node)
    {
        defaultCase(node);
    }

    public void caseAPrimfnValue(APrimfnValue node)
    {
        defaultCase(node);
    }

    public void caseTFloatingConstant(TFloatingConstant node)
    {
        defaultCase(node);
    }

    public void caseTVector(TVector node)
    {
        defaultCase(node);
    }

    public void caseTRef(TRef node)
    {
        defaultCase(node);
    }

    public void caseTBra(TBra node)
    {
        defaultCase(node);
    }

    public void caseTKet(TKet node)
    {
        defaultCase(node);
    }

    public void caseTSbra(TSbra node)
    {
        defaultCase(node);
    }

    public void caseTSket(TSket node)
    {
        defaultCase(node);
    }

    public void caseTColon(TColon node)
    {
        defaultCase(node);
    }

    public void caseTComma(TComma node)
    {
        defaultCase(node);
    }

    public void caseTIntlit(TIntlit node)
    {
        defaultCase(node);
    }

    public void caseTString(TString node)
    {
        defaultCase(node);
    }

    public void caseTTypeid(TTypeid node)
    {
        defaultCase(node);
    }

    public void caseTIdentifier(TIdentifier node)
    {
        defaultCase(node);
    }

    public void caseTOpidentifier(TOpidentifier node)
    {
        defaultCase(node);
    }

    public void caseTBlank(TBlank node)
    {
        defaultCase(node);
    }

    public void caseTComment(TComment node)
    {
        defaultCase(node);
    }

    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    public void defaultCase(Node node)
    {
    }
}
