/* This file was generated by SableCC (http://www.sablecc.org/). */

package ilcgasm.analysis;

import ilcgasm.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object in);
    Object getOut(Node node);
    void setOut(Node node, Object out);

    void caseStart(Start node);
    void caseAProgram(AProgram node);
    void caseAReference(AReference node);
    void caseAArray(AArray node);
    void caseAIdentifierId(AIdentifierId node);
    void caseAOpId(AOpId node);
    void caseATypeidTypes(ATypeidTypes node);
    void caseAArrayTypes(AArrayTypes node);
    void caseACartesianTypes(ACartesianTypes node);
    void caseAReftypeTypes(AReftypeTypes node);
    void caseAType(AType node);
    void caseANullParams(ANullParams node);
    void caseAListParams(AListParams node);
    void caseATypetail(ATypetail node);
    void caseACartval(ACartval node);
    void caseACarttail(ACarttail node);
    void caseALow(ALow node);
    void caseAHigh(AHigh node);
    void caseARealValue(ARealValue node);
    void caseAIntValue(AIntValue node);
    void caseATypeValue(ATypeValue node);
    void caseAIdValue(AIdValue node);
    void caseAStringValue(AStringValue node);
    void caseACastValue(ACastValue node);
    void caseAFnValue(AFnValue node);
    void caseAProcValue(AProcValue node);
    void caseAPrimfnValue(APrimfnValue node);

    void caseTFloatingConstant(TFloatingConstant node);
    void caseTVector(TVector node);
    void caseTRef(TRef node);
    void caseTBra(TBra node);
    void caseTKet(TKet node);
    void caseTSbra(TSbra node);
    void caseTSket(TSket node);
    void caseTColon(TColon node);
    void caseTComma(TComma node);
    void caseTIntlit(TIntlit node);
    void caseTString(TString node);
    void caseTTypeid(TTypeid node);
    void caseTIdentifier(TIdentifier node);
    void caseTOpidentifier(TOpidentifier node);
    void caseTBlank(TBlank node);
    void caseTComment(TComment node);
    void caseEOF(EOF node);
}
