#!/bin/bash
echo Running ISO Pascal acceptance tests on many cpus
echo using the Vector Pascal Compiler
echo conformance test numbers above 500 are Vector Pascal specific
for cpu in  AMD64 C64  gnuPentium  
do
 testcpu $cpu
 
 
done
