#!/bin/bash
echo Running acceptance tests on $1
rm $1.txt
rm $1.log
echo compiler output of all $1 tests will be in $1$2.log
echo program output will go to the consol and to $1$2.txt
 
lscpu|grep "Model name" >>$1.txt
for file in *.pas 
do
  
 base=$(echo $file | cut -f 1 -d '.')
 echo  $base
 echo compile $2  $base    >> $1$2.log
 time vpc $base $2  -cpu$1  >>$1$2.log
 echo execute $base >> $1$2.txt
 $base >> $1$2.txt
 $base
 rm $base $base.lis $base.lst
done
