77[1,2]EDTCOM.MSG
001	Illegal text buffer name.$
	A text buffer name may consist only of
	from one to six alphanumeric characters.$
	A text buffer name must be preceded by either '=' or '%BUF'.$
002	Bad Range Format.$
	The range you specified is not legal.$
003	Buffer Specification Conflict.$
	The command you typed implied more than one
	buffer specification.$
	For instance, this may occur by using "N:M"
	in the same line as "%L".$
004	String search cannot have a modifier.$
005	No repetition count allowed.$
006	No string-type allowed.$
007	Can't open indirect file.$
	Indirect files not yet implemented.$
008	Command I/O error.$
009	^C$
010	FATAL - Editor consistency error.$
011	Destination range must be contiguous.$
	A MOVE or COPY command can have only one destination.$
012	Illegal command option.$
013	Indirect file already open.$
014	File name wild cards not allowed.$
	An explicit file must be specified to the editor.$
015	File open error.$
	The editor is unable to correctly open the requested file.$
016	File name syntax error.$
	The file name you specified does not have the correct format.$
017	No room in output file.$
	The device is full, the editor is unable to generate the
	output file.$
018	Illegal subcommand.$
019	Repetition count cannot be zero or negative.$
020	Illegal line number.$
	A line number nust be in the range 1 to 65535.$
021	Missing string quote.$
	A legal string must be surrounded by a pair of
	matching quote marks.$
	A quoted string consists of one or more characters
	delimited by " or '.  For instance, "ABC" or 'DEF'.$
022	Range not allowed here.$
	The command you typed does not allow a range specification.$
023	Illegal string delimiters.$
	The string delimiter may not be an alphanumeric character.$
024	Illegal search string.$
025	Indirect file depth exceeded.$
	Too many nested uses of indirect files were attempted.$
026	Bad option format.$
	An editor option is of the form /xx.$
027	Illegal option name modifier.$
	An option name modifier can consist only of a "-"
	preceding the option.$
028	Unrecognized option name.$
	The option name you specified could not be recognized.$
029	Cannot mix "-" and value in option.$
	An option cannot have a modifier as well as a value.$
030	Bad option value.$
031	Only one value allowed.$
	This option only allows one value to be specified.$
032	No value specified.$
	This option requires a value.$
033	No value allowed.$
	A value has no meaning for this option.$
034	"%LAST" has no meaning in this context.$
035	Illegal termination of command line.$
	A line was terminated by other than an end of line
	or comment.$
036	FATAL - work file memory error.$
037	You must specify a source range.$
	The MOVE or COPY command requires a source range specification.$
038	An argument is required.$
039	No room for buffer.$
	The number of buffers allowed by the editor has been exceeded.$
040	Cannot yet be performed on hard copy devices.$
	The CHANGE command will not work on hard copy devices.$
041	Non-contiguous range not allowed.$
	The CHANGE command will work only on a contiguous range of lines.$
042	FATAL - Dynamic memory overflow.$
043	No output file specified.$
	The command you specified requires an output file.$
044	File name table exhausted.$
	You have explicitly referenced more files than the
	editor tables can accomodate.$
045	No input file specified.$
	"INCLUDE" or "RESTORE" requires the /FI switch to specify
	the input file.$
046	No such line.$
	The line you requested was not there.$
047	No such file.$
	The input file you requested does not exist.$
048	No line numbers allowed.$
	Line numbers have been turned off.$
049	Memory overflow.$
	The editor's memory is full.  No additional text will
	fit.  Use WRITE if you desire to save what already
	exists.$
050	No such string in this range.$
051	Illegal form for N:M.$
052	Not Yet Implemented.$
	It isn't there yet.$
	It still isn't there.$
053	Offset must be non-zero.$
	A range offset must be non-zero,
	i. e. - it may be +1 or -1, but not +0 or -0.$
054	Output file error.$
	The editor was unable to generate the output file
	without error.$
055	Incorrect fill count value.$
056	The /QUERY switch cannot be used here.$
	The XEQ command and /QUERY are incompatible.$
057	/QUERY value unrecognized.$
058	Input record too big.$
	The editor was unable to read the input record because of its
	size.$
059	No destination range.$
	In MOVE or COPY, a destination range must always exist.$
060	Ranges overlap.$
	The range specifications in the MOVE or COPY command cannot overlap.$
061	Object-string required with "%ALL".$
	When typing "%ALL", a string must be specified as a
	search object.$
062	Not a SAVE file.$
	Cannot RESTORE a non-SAVEed file.$
	RESTORE can only be used on a file which was generated by
	the SAVE command.$
063	Range must have at least one line.$
	Zero lines cannot be moved or copied.$
064	RESTORE must be first command issued.$
	No editing is allowed preceding a RESTORE command.$
	The RESTORE must be the first command of an editing session,
	nothing may precede it.$
065	Not legal here.$
	"SUBSTITUTE NEXT" can be used only after "SUBSTITUTE".$
	"SUBSTITUTE NEXT" has no meaning unless a prior
	"SUBSTITUTE" command has been executed to establish the object
	and replacement strings.$
066	I/O error on source file.$
067	No previous string entered.$
	'' or "" cannot be used unless a previous string was specified.$
068	String too long.$
069	No range specification allowed.$
	A range specification is not meaningful in SAVE or RESTORE.$
	SAVE and RESTORE only work on the entire state of the edit.$
070	Cannot recognize terminal type.$
	The terminal type you specified was unrecognizable.$
	The legal terminal types are HCPY, LA30, LA36, VT05, VT50,
	VT52, VT55, VT61.$
071	Unrecognized command.$
	The command you typed is not a legal editor command.$
072	FATAL - Work file consistency error.$
073	FATAL - I/O error on work file.$
074	FATAL - Open error on work file.$
075	XEQ range non-contiguous.$
	A range specification in XEQ must always be a
	contiguous block of lines.$
076	Nested XEQ not yet implemented.$
	This version of the editor allows no XEQ command nesting.$
077	Range required.$
	The XEQ command always requires an explicit range specification.$
$$$$

