
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Nov 09 11:43:39 GMT 2004
//----------------------------------------------------

package matlab;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 40;
  public static final int STRING_LITERAL = 4;
  public static final int SLASH = 22;
  public static final int BACKSLASH = 23;
  public static final int FOR = 36;
  public static final int MINUS = 27;
  public static final int CR = 43;
  public static final int GE_OP = 10;
  public static final int STAR = 18;
  public static final int TILDA = 28;
  public static final int SEMICOLON = 31;
  public static final int ELSEIF = 34;
  public static final int LT = 19;
  public static final int NE_OP = 12;
  public static final int COMMA = 17;
  public static final int ARRAYPOW = 6;
  public static final int PLUS = 26;
  public static final int IF = 32;
  public static final int AMPERSAND = 29;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int error = 1;
  public static final int ARRAYRDIV = 8;
  public static final int HAT = 24;
  public static final int VBAR = 21;
  public static final int GLOBAL = 44;
  public static final int BREAK = 37;
  public static final int CONSTANT = 3;
  public static final int EQ = 30;
  public static final int COLON = 25;
  public static final int LBRACE = 15;
  public static final int ELSE = 33;
  public static final int ARRAYDIV = 7;
  public static final int EQ_OP = 11;
  public static final int NCTRANSPOSE = 42;
  public static final int WHILE = 35;
  public static final int TRANSPOSE = 41;
  public static final int CLEAR = 45;
  public static final int RBRACE = 16;
  public static final int END = 39;
  public static final int ARRAYMUL = 5;
  public static final int LE_OP = 9;
  public static final int KET = 14;
  public static final int BRA = 13;
  public static final int GT = 20;
  public static final int IDENTIFIER = 2;
}

