%ifndef bmp
%define bmp ; defined by walker;0
section .text  ;0
; procedure generated by code generator class ilcg.tree.PentiumCG;0
labelff69eb88c524:;0
;	 sharpen;0
; entering a procedure at lexical level 1;0
 enter spaceforsharpenl0-4*1,1;0
; #348;0
 mov DWORD  [  ebp+     -8],     1;0
; #349;0
 floadlit -0.25;2
 sub esp,4;0
 fstp dword [esp];2
 push DWORD      1065319662;0
 floadlit -0.25;2
 sub esp,4;0
 fstp dword [esp];2
 push DWORD  [  ebp+     8];0
 call labelff69eb88c530;4
 add esp, 16;0
; #351;0
 push DWORD  [  ebp+     8];0
 push DWORD  [  ebp+     8];0
 push DWORD      1081711002;0
 call labelff69eb88c51e;4
 add esp, 12;0
 labelff69ebaecbac:;0
spaceforsharpenl0 equ 8;0
sharpenl0exit:;0
leave;0
 ret 0;4
section .text  ;0
; procedure generated by code generator class ilcg.tree.PentiumCG;0
labelff69eb88c52a:;0
;	 blur;0
; entering a procedure at lexical level 1;0
 enter spaceforblurl1-4*1,1;0
; #343;0
 push DWORD      1048576000;0
 push DWORD      1056964608;0
 push DWORD      1048576000;0
 push DWORD  [  ebp+     8];0
 call labelff69eb88c530;4
 add esp, 16;0
; #343;0
 labelff69ebaecba4:;0
spaceforblurl1 equ 4;0
blurl1exit:;0
leave;0
 ret 0;4
section .text  ;0
; procedure generated by code generator class ilcg.tree.PentiumCG;0
labelff69eb88c530:;0
;	 pconv;0
; entering a procedure at lexical level 1;0
 enter   0,1;0
 sub esp,spaceforpconvl2;0
; #329;0
 push DWORD      24;0
 lea edi,[  ebp+     -12];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_getmem;0
%define defined_getmem ; defined by walker;0
EXTERN	 _getmem;0
%endif;0
 call _getmem; imported;4
 add esp, 8;0
 mov edi,DWORD  [  ebp+     -12];0
 mov DWORD  [  edi+     4],     0;0
 mov edi,DWORD  [  ebp+     -12];0
 mov esi,DWORD  [  ebp+     8];0
 mov esi,DWORD  [  esi+     20];0
 mov DWORD  [  edi+     8],esi;0
 mov edi,DWORD  [  ebp+     -12];0
 mov DWORD  [  edi+     16],     0;0
 mov edi,DWORD  [  ebp+     -12];0
 mov esi,DWORD  [  ebp+     8];0
 mov esi,DWORD  [  esi+     32];0
 mov DWORD  [  edi+     20],esi;0
 push DWORD      1;0
 push DWORD      2;0
 lea edi,[  ebp+     -12];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_initvec;0
%define defined_initvec ; defined by walker;0
EXTERN	 _initvec;0
%endif;0
 call _initvec; imported;4
 add esp, 12;0
; #330;0
 push DWORD      24;0
 lea edi,[  ebp+     -16];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_getmem;0
%define defined_getmem ; defined by walker;0
EXTERN	 _getmem;0
%endif;0
 call _getmem; imported;4
 add esp, 8;0
 mov edi,DWORD  [  ebp+     -16];0
 mov DWORD  [  edi+     4],     0;0
 mov edi,DWORD  [  ebp+     -16];0
 mov DWORD  [  edi+     8],     3;0
 mov edi,DWORD  [  ebp+     -16];0
 mov DWORD  [  edi+     16],     0;0
 mov edi,DWORD  [  ebp+     -16];0
 mov esi,DWORD  [  ebp+     8];0
 mov esi,DWORD  [  esi+     32];0
 mov DWORD  [  edi+     20],esi;0
 push DWORD      1;0
 push DWORD      2;0
 lea edi,[  ebp+     -16];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_initvec;0
%define defined_initvec ; defined by walker;0
EXTERN	 _initvec;0
%endif;0
 call _initvec; imported;4
 add esp, 12;0
; #331;0
 xor edi,edi;0
 mov esi,DWORD  [  ebp+     -16];0
 cmp edi,dword    [  esi+     8];0
 jg near  labelff69ebb160ba;0
 jmp  labelff69ebb160bc;0
 labelff69ebb160ba:;0
 push DWORD      331;0
 push DWORD      201;0
 call labelff68bae2fa230;4
 add esp, 8;0
 labelff69ebb160bc:;0
 mov edi,DWORD  [  ebp+     -16];0
 mov edi,DWORD  [ edi];0
 mov DWORD  [  ebp+     -36],edi;0
 mov DWORD  [  ebp+     -32],     0;0
 mov edi,DWORD  [  ebp+     -16];0
 mov edi,DWORD  [  edi+     20];0
 mov DWORD  [  ebp+     -28],edi;0
 ;0
 mov DWORD  [  ebp+     -44],edi;0
 mov DWORD  [  ebp+     -40],     0;0
 labelff69ebb174be:;0
 mov edi,DWORD  [  ebp+     -40];0
 cmp edi,dword    [  ebp+     -44];0
 jg near  labelff69ebb174c0;0
 mov edi,DWORD  [  ebp+     -36];0
 mov esi,DWORD  [  ebp+     -40];0
 fld dword  [  ebp+     12];2
 floadlit -1.0;2
 fcom st0,st1  ;2
push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jnb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 1.0;2
 fcom st0,st1  ;2
 push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 127.5;2
 fmulp st1;2
 floadlit -0.5;2
 faddp st1;2
  frndint;2
 sub esp,4;0
 fistp dword [esp];2
 pop  ebx;0
 mov dword[fttemp], ebx;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 pop  ebx;0
 mov BYTE  [  edi+esi],bl;0
 inc DWORD  [  ebp+     -40];0
 jmp  labelff69ebb174be;0
 labelff69ebb174c0:;0
; #331;0
 mov DWORD edi,     1;0
 mov esi,DWORD  [  ebp+     -16];0
 cmp edi,dword    [  esi+     8];0
 jg near  labelff69ebb1f7c2;0
 jmp  labelff69ebb1f7c4;0
 labelff69ebb1f7c2:;0
 push DWORD      331;0
 push DWORD      201;0
 call labelff68bae2fa230;4
 add esp, 8;0
 labelff69ebb1f7c4:;0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     -16];0
 mov edi,DWORD  [  eax+     12];0
 mov esi,DWORD  [ eax];0
 lea edi,[  edi+esi];0
 mov DWORD  [  ebp+     -72],edi;0
 mov DWORD  [  ebp+     -68],     0;0
 mov edi,DWORD  [  ebp+     -16];0
 mov edi,DWORD  [  edi+     20];0
 mov DWORD  [  ebp+     -64],edi;0
 ;0
 mov DWORD  [  ebp+     -80],edi;0
 mov DWORD  [  ebp+     -76],     0;0
 labelff69ebb215c6:;0
 mov edi,DWORD  [  ebp+     -76];0
 cmp edi,dword    [  ebp+     -80];0
 jg near  labelff69ebb215c8;0
 mov edi,DWORD  [  ebp+     -72];0
 mov esi,DWORD  [  ebp+     -76];0
 fld dword  [  ebp+     16];2
 floadlit -1.0;2
 fcom st0,st1  ;2
push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jnb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 1.0;2
 fcom st0,st1  ;2
 push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 127.5;2
 fmulp st1;2
 floadlit -0.5;2
 faddp st1;2
  frndint;2
 sub esp,4;0
 fistp dword [esp];2
 pop  ebx;0
 mov BYTE  [  edi+esi],bl;0
 inc DWORD  [  ebp+     -76];0
 jmp  labelff69ebb215c6;0
 labelff69ebb215c8:;0
; #331;0
 mov DWORD edi,     2;0
 mov esi,DWORD  [  ebp+     -16];0
 cmp edi,dword    [  esi+     8];0
 jg near  labelff69ebb23dca;0
 jmp  labelff69ebb23dcc;0
 labelff69ebb23dca:;0
 push DWORD      331;0
 push DWORD      201;0
 call labelff68bae2fa230;4
 add esp, 8;0
 labelff69ebb23dcc:;0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     -16];0
 mov esi,DWORD  [ eax];0
 mov ebx,DWORD  [  eax+     12];0
 lea edi,[  esi+ ebx* 2];0
 mov DWORD  [  ebp+     -108],edi;0
 mov DWORD  [  ebp+     -104],     0;0
 mov edi,DWORD  [  ebp+     -16];0
 mov edi,DWORD  [  edi+     20];0
 mov DWORD  [  ebp+     -100],edi;0
 ;0
 mov DWORD  [  ebp+     -116],edi;0
 mov DWORD  [  ebp+     -112],     0;0
 labelff69ebb26fce:;0
 mov edi,DWORD  [  ebp+     -112];0
 cmp edi,dword    [  ebp+     -116];0
 jg near  labelff69ebb26fd0;0
 mov edi,DWORD  [  ebp+     -108];0
 mov esi,DWORD  [  ebp+     -112];0
 fld dword  [  ebp+     20];2
 floadlit -1.0;2
 fcom st0,st1  ;2
push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jnb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 1.0;2
 fcom st0,st1  ;2
 push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 127.5;2
 fmulp st1;2
 floadlit -0.5;2
 faddp st1;2
  frndint;2
 sub esp,4;0
 fistp dword [esp];2
 pop  ebx;0
 mov BYTE  [  edi+esi],bl;0
 inc DWORD  [  ebp+     -112];0
 jmp  labelff69ebb26fce;0
 labelff69ebb26fd0:;0
; #336;0
 mov DWORD  [  ebp+     -164],     0;0
 mov edi,DWORD  [  ebp+     8];0
 mov edi,DWORD  [  edi+     20];0
 mov DWORD  [  ebp+     -160],edi;0
 mov edi,DWORD  [  ebp+     8];0
 mov edi,DWORD  [  edi+     24];0
 mov DWORD  [  ebp+     -156],edi;0
 mov DWORD  [  ebp+     -152],     0;0
 mov edi,DWORD  [  ebp+     8];0
 mov edi,DWORD  [  edi+     32];0
 mov DWORD  [  ebp+     -148],edi;0
 mov edi,DWORD  [  ebp+     8];0
 mov edi,DWORD  [  edi+     8];0
 mov DWORD  [  ebp+     -132],edi;0
 mov DWORD  [  ebp+     -8],     0;0
 labelff69ebb2abd2:;0
 mov edi,DWORD  [  ebp+     -8];0
 cmp edi,dword    [  ebp+     -132];0
 jg near  labelff69ebb2abd4;0
 mov edi,DWORD  [  ebp+     8];0
 mov edi,DWORD  [  edi+     8];0
 cmp edi,dword    [  ebp+     -8];0
 jl near  labelff69ebb2c9d6;0
 jmp  labelff69ebb2c9d8;0
 labelff69ebb2c9d6:;0
 push DWORD      336;0
 mov edi,DWORD  [  ebp+     8];0
 push DWORD  [  edi+     8];0
 mov edi,DWORD  [  ebp+     8];0
 push DWORD  [  edi+     8];0
 push DWORD  [  ebp+     -8];0
 call labelff68bae2c846;4
 add esp, 16;0
 labelff69ebb2c9d8:;0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     8];0
 mov edi,DWORD  [  ebp+     -8];0
 imul  edi, [  eax+     12];0
 mov esi,DWORD  [ eax];0
 lea edi,[  edi+esi];0
 mov DWORD  [  ebp+     -168],edi;0
 push DWORD  [  ebp+     -12];0
 push DWORD  [  ebp+     -16];0
 lea edi,[  ebp+     -168];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 call labelff69eb9f3098;4
 add esp, 12;0
 inc DWORD  [  ebp+     -8];0
 jmp  labelff69ebb2abd2;0
 labelff69ebb2abd4:;0
; #338;0
 push DWORD      4;0
 lea edi,[  ebp+     -16];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_freemem;0
%define defined_freemem ; defined by walker;0
EXTERN	 _freemem;0
%endif;0
 call _freemem; imported;4
 add esp, 8;0
; #339;0
 push DWORD      4;0
 lea edi,[  ebp+     -12];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_freemem;0
%define defined_freemem ; defined by walker;0
EXTERN	 _freemem;0
%endif;0
 call _freemem; imported;4
 add esp, 8;0
; #340;0
 labelff69eb9f3094:;0
spaceforpconvl2 equ 168;0
pconvl2exit:;0
leave;0
 ret 0;4
section .text  ;0
; procedure generated by code generator class ilcg.tree.PentiumCG;0
labelff69eb9f3098:;0
;	 convp;0
; entering a procedure at lexical level 2;0
 enter   0,2;0
 sub esp,spaceforconvpl3;0
; #309;0
 mov edi,DWORD  [  ebp+     8];0
 mov edi,DWORD  [  edi+     8];0
 mov DWORD  [  ebp+     -12],edi;0
; #310;0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     16];0
 mov edi,DWORD  [  eax+     12];0
 mov esi,DWORD  [ eax];0
 lea edi,[  edi+esi];0
 mov DWORD  [  ebp+     -48],edi;0
 mov DWORD  [  ebp+     -44],     0;0
 mov edi,DWORD  [  ebp+     -12];0
 lea edi,[  edi+     -2];0
 mov DWORD  [  ebp+     -40],edi;0
 mov edi,DWORD  [  ebp+     16];0
 mov edi,DWORD  [  edi+     12];0
 mov DWORD  [  ebp+     -36],edi;0
 mov DWORD  [  ebp+     -32],     0;0
 mov edi,DWORD  [  ebp+     16];0
 mov edi,DWORD  [  edi+     20];0
 mov DWORD  [  ebp+     -28],edi;0
 mov DWORD  [  ebp+     -52],     0;0
 labelff69ebb387de:;1
 mov edi,DWORD  [  ebp+     -52];1
 mov esi,DWORD  [  ebp+     -12];1
 lea esi,[  esi+     -2];1
 cmp edi,dword   esi;1
 jg near  labelff69ebb387e0;1
 mov DWORD  [  ebp+     -92],     0;1
 mov DWORD  [  ebp+     -80],     0;1
 mov edi,DWORD  [  ebp+     12];1
 mov edi,DWORD  [ edi];1
 mov DWORD  [  ebp+     -108],edi;1
 mov DWORD  [  ebp+     -104],     0;1
 mov edi,DWORD  [  ebp+     12];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -100],edi;1
 mov edi,DWORD  [  ebp+     -28];1
 inc DWORD edi;1
 shr edi,      3;1
 lea edi,[   edi* 8+     -1];1
 mov DWORD  [  ebp+     -120],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [ edi];1
 mov DWORD  [  ebp+     -96],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -88],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -84],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -76],edi;1
 mov DWORD  [  ebp+     -56],     0;1
 labelff69ebb3e1e2:;1
 mov edi,DWORD  [  ebp+     -56];1
 cmp edi,dword    [  ebp+     -120];1
 jg near  labelff69ebb3e1e4;1
; #substituting in eax with 3 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     -56];1
 mov edi,DWORD  [  ebp+     -52];1
 imul  edi, [  ebp+     -36];1
 mov esi,DWORD  [  ebp+     -48];1
 lea esi,[  esi+eax];1
 lea edi,[  edi+esi];1
 mov esi,DWORD  [  ebp+     -52];1
 imul  esi, [  ebp+     -84];1
 mov ebx,DWORD  [  ebp+     -96];1
 lea ebx,[  ebx+eax];1
 movq MM4, [  esi+ebx];1
 mov esi,DWORD  [  ebp+     -108];1
 pxor MM7,MM7;1
 pxor MM5,MM5;1
 punpckhbw MM7, [  esi+eax];1
 pxor MM6,MM6;1
 punpckhbw MM6,MM4;1
 punpcklbw MM5, [  esi+eax];1
 pmulhw MM7,MM6;1
 psraw MM7,7;1
 pxor MM6,MM6;1
 punpcklbw MM6,MM4;1
 pmulhw MM5,MM6;1
 psraw MM5,7;1
 packsswb MM5,MM7;1
 movq MM4,MM5;1
 movq  [ edi],MM4;1
 add  DWORD  [  ebp+     -56],     8;1
 jmp  labelff69ebb3e1e2;1
 labelff69ebb3e1e4:;1
 mov edi,DWORD  [  ebp+     -28];1
 inc DWORD edi;1
 shr edi,      3;1
 imul edi,DWORD edi,    8;1
 mov DWORD  [  ebp+     -56],edi;1
 labelff69ebb52ce6:;1
 mov edi,DWORD  [  ebp+     -56];1
 cmp edi,dword    [  ebp+     -28];1
 jg near  labelff69ebb52ce8;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [ edi];1
 mov DWORD  [  ebp+     -96],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -88],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -84],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -76],edi;1
; #substituting in eax with 3 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     -56];1
 mov edi,DWORD  [  ebp+     -52];1
 imul  edi, [  ebp+     -36];1
 lea edi,[  edi+eax];1
 mov esi,DWORD  [  ebp+     -48];1
 mov ebx,DWORD  [  ebp+     -52];1
 imul  ebx, [  ebp+     -84];1
 mov ecx,DWORD  [  ebp+     -96];1
 lea ecx,[  ecx+eax];1
 mov bl,byte  [  ebx+ecx];1
 mov ecx,DWORD  [  ebp+     -108];1
 mov bh,byte  [  ecx+eax];1
 push ax;1
 mov al,bh;1
 imul  bl;1
 shr ax,7;1
 mov bl,al;1
 pop ax;1
 mov BYTE  [  edi+esi],bl;1
 inc DWORD  [  ebp+     -56];1
 jmp  labelff69ebb52ce6;1
 labelff69ebb52ce8:;1
 inc DWORD  [  ebp+     -52];1
 jmp  labelff69ebb387de;1
 labelff69ebb387e0:;1
; #311;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  eax+     12];1
 mov esi,DWORD  [ eax];1
 lea edi,[  edi+esi];1
 mov DWORD  [  ebp+     -168],edi;1
 mov DWORD  [  ebp+     -164],     0;1
 mov edi,DWORD  [  ebp+     -12];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -160],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -156],edi;1
 mov DWORD  [  ebp+     -152],     0;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -148],edi;1
 mov DWORD  [  ebp+     -172],     0;1
 labelff69ebb6d0ea:;1
 mov edi,DWORD  [  ebp+     -172];1
 mov esi,DWORD  [  ebp+     -12];1
 lea esi,[  esi+     -2];1
 cmp edi,dword   esi;1
 jg near  labelff69ebb6d0ec;1
 mov DWORD  [  ebp+     -212],     0;1
 mov DWORD  [  ebp+     -200],     0;1
 mov DWORD  [  ebp+     -236],     0;1
 mov DWORD  [  ebp+     -224],     0;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     12];1
 mov edi,DWORD  [  eax+     12];1
 mov esi,DWORD  [ eax];1
 lea edi,[  edi+esi];1
 mov DWORD  [  ebp+     -252],edi;1
 mov DWORD  [  ebp+     -248],     0;1
 mov edi,DWORD  [  ebp+     12];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -244],edi;1
 mov edi,DWORD  [  ebp+     -148];1
 inc DWORD edi;1
 shr edi,      3;1
 lea edi,[   edi* 8+     -1];1
 mov DWORD  [  ebp+     -264],edi;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  eax+     12];1
 mov esi,DWORD  [ eax];1
 lea edi,[  edi+esi];1
 mov DWORD  [  ebp+     -216],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -208],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -204],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -196],edi;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  eax+     12];1
 mov esi,DWORD  [ eax];1
 lea edi,[  edi+esi];1
 mov DWORD  [  ebp+     -240],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -232],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -228],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -220],edi;1
 mov DWORD  [  ebp+     -176],     0;1
 labelff69ebb72bee:;1
 mov edi,DWORD  [  ebp+     -176];1
 cmp edi,dword    [  ebp+     -264];1
 jg near  labelff69ebb72bf0;1
; #substituting in eax with 4 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     -176];1
 mov edi,DWORD  [  ebp+     -172];1
 imul  edi, [  ebp+     -156];1
 mov esi,DWORD  [  ebp+     -168];1
 lea esi,[  esi+eax];1
 lea edi,[  edi+esi];1
 mov esi,DWORD  [  ebp+     -172];1
 imul  esi, [  ebp+     -204];1
 mov ebx,DWORD  [  ebp+     -216];1
 lea ebx,[  ebx+eax];1
 movq MM4, [  esi+ebx];1
 mov esi,DWORD  [  ebp+     -172];1
 imul  esi, [  ebp+     -228];1
 mov ebx,DWORD  [  ebp+     -240];1
 lea ebx,[  ebx+eax];1
 movq MM3, [  esi+ebx];1
 mov esi,DWORD  [  ebp+     -252];1
 pxor MM7,MM7;1
 pxor MM5,MM5;1
 punpckhbw MM7, [  esi+eax];1
 pxor MM6,MM6;1
 punpckhbw MM6,MM3;1
 punpcklbw MM5, [  esi+eax];1
 pmulhw MM7,MM6;1
 psraw MM7,7;1
 pxor MM6,MM6;1
 punpcklbw MM6,MM3;1
 pmulhw MM5,MM6;1
 psraw MM5,7;1
 packsswb MM5,MM7;1
 movq MM3,MM5;1
 paddsb MM4,MM3;1
 movq  [ edi],MM4;1
 add  DWORD  [  ebp+     -176],     8;1
 jmp  labelff69ebb72bee;1
 labelff69ebb72bf0:;1
 mov edi,DWORD  [  ebp+     -148];1
 inc DWORD edi;1
 shr edi,      3;1
 imul edi,DWORD edi,    8;1
 mov DWORD  [  ebp+     -176],edi;1
 labelff69ebb983f2:;1
 mov edi,DWORD  [  ebp+     -176];1
 cmp edi,dword    [  ebp+     -148];1
 jg near  labelff69ebb983f4;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  eax+     12];1
 mov esi,DWORD  [ eax];1
 lea edi,[  edi+esi];1
 mov DWORD  [  ebp+     -216],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -208],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -204],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -196],edi;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  eax+     12];1
 mov esi,DWORD  [ eax];1
 lea edi,[  edi+esi];1
 mov DWORD  [  ebp+     -240],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -232],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -228],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -220],edi;1
 mov edi,DWORD  [  ebp+     -172];1
 imul  edi, [  ebp+     -156];1
 mov esi,DWORD  [  ebp+     -176];1
 lea edi,[  edi+esi];1
 mov esi,DWORD  [  ebp+     -168];1
 mov ebx,DWORD  [  ebp+     -172];1
 imul  ebx, [  ebp+     -204];1
 mov eax,DWORD  [  ebp+     -176];1
 lea ebx,[  ebx+eax];1
 mov eax,DWORD  [  ebp+     -216];1
 mov bl,byte  [  ebx+eax];1
 mov eax,DWORD  [  ebp+     -172];1
 imul  eax, [  ebp+     -228];1
 mov ecx,DWORD  [  ebp+     -176];1
 lea eax,[  eax+ecx];1
 mov ecx,DWORD  [  ebp+     -240];1
 mov dl,byte  [  eax+ecx];1
 mov ecx,DWORD  [  ebp+     -252];1
 add ecx, [  ebp+     -176];1
 mov bh,byte  [ ecx];1
 push ax;1
 mov al,bh;1
 imul  dl;1
 shr ax,7;1
 mov dl,al;1
 pop ax;1
 add  bl,dl;1
 jno $+10;1
 jg $+6;1
 mov bl ,-128 ;1
 jng $+4;1
 mov bl,127;1
 ;1
 mov BYTE  [  edi+esi],bl;1
 inc DWORD  [  ebp+     -176];1
 jmp  labelff69ebb983f2;1
 labelff69ebb983f4:;1
 inc DWORD  [  ebp+     -172];1
 jmp  labelff69ebb6d0ea;1
 labelff69ebb6d0ec:;1
; #312;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  eax+     12];1
 mov esi,DWORD  [ eax];1
 lea edi,[  edi+esi];1
 mov DWORD  [  ebp+     -312],edi;1
 mov DWORD  [  ebp+     -308],     0;1
 mov edi,DWORD  [  ebp+     -12];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -304],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -300],edi;1
 mov DWORD  [  ebp+     -296],     0;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -292],edi;1
 mov DWORD  [  ebp+     -316],     0;1
 labelff69ebc81bf6:;1
 mov edi,DWORD  [  ebp+     -316];1
 mov esi,DWORD  [  ebp+     -12];1
 lea esi,[  esi+     -2];1
 cmp edi,dword   esi;1
 jg near  labelff69ebc81bf8;1
 mov DWORD  [  ebp+     -356],     0;1
 mov DWORD  [  ebp+     -344],     0;1
 mov DWORD  [  ebp+     -380],     0;1
 mov DWORD  [  ebp+     -368],     0;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     12];1
 mov esi,DWORD  [ eax];1
 mov ebx,DWORD  [  eax+     12];1
 lea edi,[  esi+ ebx* 2];1
 mov DWORD  [  ebp+     -396],edi;1
 mov DWORD  [  ebp+     -392],     0;1
 mov edi,DWORD  [  ebp+     12];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -388],edi;1
 mov edi,DWORD  [  ebp+     -292];1
 inc DWORD edi;1
 shr edi,      3;1
 lea edi,[   edi* 8+     -1];1
 mov DWORD  [  ebp+     -408],edi;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  eax+     12];1
 mov esi,DWORD  [ eax];1
 lea edi,[  edi+esi];1
 mov DWORD  [  ebp+     -360],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -352],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -348],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -340],edi;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     8];1
 mov esi,DWORD  [ eax];1
 mov ebx,DWORD  [  eax+     12];1
 lea edi,[  esi+ ebx* 2];1
 mov DWORD  [  ebp+     -384],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -376],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -372],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -364],edi;1
 mov DWORD  [  ebp+     -320],     0;1
 labelff69ebc861fa:;1
 mov edi,DWORD  [  ebp+     -320];1
 cmp edi,dword    [  ebp+     -408];1
 jg near  labelff69ebc861fc;1
; #substituting in eax with 4 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     -320];1
 mov edi,DWORD  [  ebp+     -316];1
 imul  edi, [  ebp+     -300];1
 mov esi,DWORD  [  ebp+     -312];1
 lea esi,[  esi+eax];1
 lea edi,[  edi+esi];1
 mov esi,DWORD  [  ebp+     -316];1
 imul  esi, [  ebp+     -348];1
 mov ebx,DWORD  [  ebp+     -360];1
 lea ebx,[  ebx+eax];1
 movq MM4, [  esi+ebx];1
 mov esi,DWORD  [  ebp+     -316];1
 imul  esi, [  ebp+     -372];1
 mov ebx,DWORD  [  ebp+     -384];1
 lea ebx,[  ebx+eax];1
 movq MM3, [  esi+ebx];1
 mov esi,DWORD  [  ebp+     -396];1
 pxor MM7,MM7;1
 pxor MM5,MM5;1
 punpckhbw MM7, [  esi+eax];1
 pxor MM6,MM6;1
 punpckhbw MM6,MM3;1
 punpcklbw MM5, [  esi+eax];1
 pmulhw MM7,MM6;1
 psraw MM7,7;1
 pxor MM6,MM6;1
 punpcklbw MM6,MM3;1
 pmulhw MM5,MM6;1
 psraw MM5,7;1
 packsswb MM5,MM7;1
 movq MM3,MM5;1
 paddsb MM4,MM3;1
 movq  [ edi],MM4;1
 add  DWORD  [  ebp+     -320],     8;1
 jmp  labelff69ebc861fa;1
 labelff69ebc861fc:;1
 mov edi,DWORD  [  ebp+     -292];1
 inc DWORD edi;1
 shr edi,      3;1
 imul edi,DWORD edi,    8;1
 mov DWORD  [  ebp+     -320],edi;1
 labelff69ebc983fe:;1
 mov edi,DWORD  [  ebp+     -320];1
 cmp edi,dword    [  ebp+     -292];1
 jg near  labelff69ebc983100;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  eax+     12];1
 mov esi,DWORD  [ eax];1
 lea edi,[  edi+esi];1
 mov DWORD  [  ebp+     -360],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -352],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -348],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -340],edi;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     8];1
 mov esi,DWORD  [ eax];1
 mov ebx,DWORD  [  eax+     12];1
 lea edi,[  esi+ ebx* 2];1
 mov DWORD  [  ebp+     -384],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -376],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -372],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -364],edi;1
 mov edi,DWORD  [  ebp+     -316];1
 imul  edi, [  ebp+     -300];1
 mov esi,DWORD  [  ebp+     -320];1
 lea edi,[  edi+esi];1
 mov esi,DWORD  [  ebp+     -312];1
 mov ebx,DWORD  [  ebp+     -316];1
 imul  ebx, [  ebp+     -348];1
 mov eax,DWORD  [  ebp+     -320];1
 lea ebx,[  ebx+eax];1
 mov eax,DWORD  [  ebp+     -360];1
 mov bl,byte  [  ebx+eax];1
 mov eax,DWORD  [  ebp+     -316];1
 imul  eax, [  ebp+     -372];1
 mov ecx,DWORD  [  ebp+     -320];1
 lea eax,[  eax+ecx];1
 mov ecx,DWORD  [  ebp+     -384];1
 mov dl,byte  [  eax+ecx];1
 mov ecx,DWORD  [  ebp+     -396];1
 add ecx, [  ebp+     -320];1
 mov bh,byte  [ ecx];1
 push ax;1
 mov al,bh;1
 imul  dl;1
 shr ax,7;1
 mov dl,al;1
 pop ax;1
 add  bl,dl;1
 jno $+10;1
 jg $+6;1
 mov bl ,-128 ;1
 jng $+4;1
 mov bl,127;1
 ;1
 mov BYTE  [  edi+esi],bl;1
 inc DWORD  [  ebp+     -320];1
 jmp  labelff69ebc983fe;1
 labelff69ebc983100:;1
 inc DWORD  [  ebp+     -316];1
 jmp  labelff69ebc81bf6;1
 labelff69ebc81bf8:;1
; #313;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [ edi];1
 mov DWORD  [  ebp+     -432],edi;1
 mov DWORD  [  ebp+     -428],     0;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -424],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [ edi];1
 mov DWORD  [  ebp+     -456],edi;1
 mov DWORD  [  ebp+     -452],     0;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -448],edi;1
 mov edi,DWORD  [  ebp+     -424];1
 inc DWORD edi;1
 shr edi,      3;1
 lea edi,[   edi* 8+     -1];1
 mov DWORD  [  ebp+     -464],edi;1
 mov DWORD  [  ebp+     -436],     0;1
 labelff69ebd2c9102:;1
 mov edi,DWORD  [  ebp+     -436];1
 cmp edi,dword    [  ebp+     -464];1
 jg near  labelff69ebd2c9104;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     -436];1
 mov edi,DWORD  [  ebp+     -432];1
 lea edi,[  edi+eax];1
 mov esi,DWORD  [  ebp+     -456];1
 movq MM4, [  esi+eax];1
 movq  [ edi],MM4;1
 add  DWORD  [  ebp+     -436],     8;1
 jmp  labelff69ebd2c9102;1
 labelff69ebd2c9104:;1
 mov edi,DWORD  [  ebp+     -424];1
 inc DWORD edi;1
 shr edi,      3;1
 imul edi,DWORD edi,    8;1
 mov DWORD  [  ebp+     -436],edi;1
 labelff69ebd2dd106:;1
 mov edi,DWORD  [  ebp+     -436];1
 cmp edi,dword    [  ebp+     -424];1
 jg near  labelff69ebd2dd108;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     -436];1
 mov edi,DWORD  [  ebp+     -432];1
 mov esi,DWORD  [  ebp+     -456];1
 mov bl,byte  [  esi+eax];1
 mov BYTE  [  edi+eax],bl;1
 inc DWORD  [  ebp+     -436];1
 jmp  labelff69ebd2dd106;1
 labelff69ebd2dd108:;1
; #314;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  ebp+     -12];1
 imul  edi, [  eax+     12];1
 mov esi,DWORD  [ eax];1
 lea edi,[  edi+esi];1
 mov DWORD  [  ebp+     -480],edi;1
 mov DWORD  [  ebp+     -476],     0;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -472],edi;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  ebp+     -12];1
 imul  edi, [  eax+     12];1
 mov esi,DWORD  [ eax];1
 lea edi,[  edi+esi];1
 mov DWORD  [  ebp+     -504],edi;1
 mov DWORD  [  ebp+     -500],     0;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -496],edi;1
 mov edi,DWORD  [  ebp+     -472];1
 inc DWORD edi;1
 shr edi,      3;1
 lea edi,[   edi* 8+     -1];1
 mov DWORD  [  ebp+     -512],edi;1
 mov DWORD  [  ebp+     -484],     0;1
 labelff69ebd37d10a:;1
 mov edi,DWORD  [  ebp+     -484];1
 cmp edi,dword    [  ebp+     -512];1
 jg near  labelff69ebd37d10c;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     -484];1
 mov edi,DWORD  [  ebp+     -480];1
 lea edi,[  edi+eax];1
 mov esi,DWORD  [  ebp+     -504];1
 movq MM4, [  esi+eax];1
 movq  [ edi],MM4;1
 add  DWORD  [  ebp+     -484],     8;1
 jmp  labelff69ebd37d10a;1
 labelff69ebd37d10c:;1
 mov edi,DWORD  [  ebp+     -472];1
 inc DWORD edi;1
 shr edi,      3;1
 imul edi,DWORD edi,    8;1
 mov DWORD  [  ebp+     -484],edi;1
 labelff69ebd39110e:;1
 mov edi,DWORD  [  ebp+     -484];1
 cmp edi,dword    [  ebp+     -472];1
 jg near  labelff69ebd391110;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     -484];1
 mov edi,DWORD  [  ebp+     -480];1
 mov esi,DWORD  [  ebp+     -504];1
 mov bl,byte  [  esi+eax];1
 mov BYTE  [  edi+eax],bl;1
 inc DWORD  [  ebp+     -484];1
 jmp  labelff69ebd39110e;1
 labelff69ebd391110:;1
; #318;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -16],edi;1
; #319;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [ edi];1
 inc DWORD edi;1
 mov DWORD  [  ebp+     -552],edi;1
 mov DWORD  [  ebp+     -548],     0;1
 mov edi,DWORD  [  ebp+     -12];1
 mov DWORD  [  ebp+     -544],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -540],edi;1
 mov DWORD  [  ebp+     -536],     0;1
 mov edi,DWORD  [  ebp+     -16];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -532],edi;1
 mov DWORD  [  ebp+     -556],     0;1
 labelff69ebd3cd112:;1
 mov edi,DWORD  [  ebp+     -556];1
 cmp edi,dword    [  ebp+     -12];1
 jg near  labelff69ebd3cd114;1
 mov DWORD  [  ebp+     -596],     0;1
 mov DWORD  [  ebp+     -584],     0;1
 mov edi,DWORD  [  ebp+     12];1
 mov edi,DWORD  [ edi];1
 mov DWORD  [  ebp+     -612],edi;1
 mov DWORD  [  ebp+     -608],     0;1
 mov edi,DWORD  [  ebp+     12];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -604],edi;1
 mov DWORD  [  ebp+     -644],     0;1
 mov DWORD  [  ebp+     -632],     0;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     12];1
 mov esi,DWORD  [ eax];1
 mov ebx,DWORD  [  eax+     12];1
 lea edi,[  esi+ ebx* 2];1
 mov DWORD  [  ebp+     -660],edi;1
 mov DWORD  [  ebp+     -656],     0;1
 mov edi,DWORD  [  ebp+     12];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -652],edi;1
 mov DWORD  [  ebp+     -692],     0;1
 mov DWORD  [  ebp+     -680],     0;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     12];1
 mov edi,DWORD  [  eax+     12];1
 mov esi,DWORD  [ eax];1
 lea edi,[  edi+esi];1
 mov DWORD  [  ebp+     -708],edi;1
 mov DWORD  [  ebp+     -704],     0;1
 mov edi,DWORD  [  ebp+     12];1
 mov edi,DWORD  [  edi+     20];1
 mov DWORD  [  ebp+     -700],edi;1
 mov edi,DWORD  [  ebp+     -16];1
 lea edi,[  edi+     -1];1
 shr edi,      3;1
 lea edi,[   edi* 8+     -1];1
 mov DWORD  [  ebp+     -720],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [ edi];1
 mov DWORD  [  ebp+     -600],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 mov DWORD  [  ebp+     -592],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -588],edi;1
 mov edi,DWORD  [  ebp+     -16];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -580],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [ edi];1
 lea edi,[  edi+     2];1
 mov DWORD  [  ebp+     -648],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 mov DWORD  [  ebp+     -640],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -636],edi;1
 mov edi,DWORD  [  ebp+     -16];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -628],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [ edi];1
 inc DWORD edi;1
 mov DWORD  [  ebp+     -696],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 mov DWORD  [  ebp+     -688],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -684],edi;1
 mov edi,DWORD  [  ebp+     -16];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -676],edi;1
 mov DWORD  [  ebp+     -560],     0;1
 labelff69ebd427116:;1
 mov edi,DWORD  [  ebp+     -560];1
 cmp edi,dword    [  ebp+     -720];1
 jg near  labelff69ebd427118;1
; #substituting in eax with 7 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     -560];1
 mov edi,DWORD  [  ebp+     -556];1
 imul  edi, [  ebp+     -540];1
 mov esi,DWORD  [  ebp+     -552];1
 lea esi,[  esi+eax];1
 lea edi,[  edi+esi];1
 mov esi,DWORD  [  ebp+     -556];1
 imul  esi, [  ebp+     -588];1
 mov ebx,DWORD  [  ebp+     -600];1
 lea ebx,[  ebx+eax];1
 movq MM4, [  esi+ebx];1
 mov esi,DWORD  [  ebp+     -612];1
 pxor MM7,MM7;1
 pxor MM5,MM5;1
 punpckhbw MM7, [  esi+eax];1
 pxor MM6,MM6;1
 punpckhbw MM6,MM4;1
 punpcklbw MM5, [  esi+eax];1
 pmulhw MM7,MM6;1
 psraw MM7,7;1
 pxor MM6,MM6;1
 punpcklbw MM6,MM4;1
 pmulhw MM5,MM6;1
 psraw MM5,7;1
 packsswb MM5,MM7;1
 movq MM4,MM5;1
 mov esi,DWORD  [  ebp+     -556];1
 imul  esi, [  ebp+     -636];1
 mov ebx,DWORD  [  ebp+     -648];1
 lea ebx,[  ebx+eax];1
 movq MM3, [  esi+ebx];1
 mov esi,DWORD  [  ebp+     -660];1
 pxor MM7,MM7;1
 pxor MM5,MM5;1
 punpckhbw MM7, [  esi+eax];1
 pxor MM6,MM6;1
 punpckhbw MM6,MM3;1
 punpcklbw MM5, [  esi+eax];1
 pmulhw MM7,MM6;1
 psraw MM7,7;1
 pxor MM6,MM6;1
 punpcklbw MM6,MM3;1
 pmulhw MM5,MM6;1
 psraw MM5,7;1
 packsswb MM5,MM7;1
 movq MM3,MM5;1
 paddsb MM4,MM3;1
 mov esi,DWORD  [  ebp+     -556];1
 imul  esi, [  ebp+     -684];1
 mov ebx,DWORD  [  ebp+     -696];1
 lea ebx,[  ebx+eax];1
 movq MM3, [  esi+ebx];1
 mov esi,DWORD  [  ebp+     -708];1
 pxor MM7,MM7;1
 pxor MM5,MM5;1
 punpckhbw MM7, [  esi+eax];1
 pxor MM6,MM6;1
 punpckhbw MM6,MM3;1
 punpcklbw MM5, [  esi+eax];1
 pmulhw MM7,MM6;1
 psraw MM7,7;1
 pxor MM6,MM6;1
 punpcklbw MM6,MM3;1
 pmulhw MM5,MM6;1
 psraw MM5,7;1
 packsswb MM5,MM7;1
 movq MM3,MM5;1
 paddsb MM4,MM3;1
 movq  [ edi],MM4;1
 add  DWORD  [  ebp+     -560],     8;1
 jmp  labelff69ebd427116;1
 labelff69ebd427118:;1
 mov edi,DWORD  [  ebp+     -16];1
 lea edi,[  edi+     -1];1
 shr edi,      3;1
 imul edi,DWORD edi,    8;1
 mov DWORD  [  ebp+     -560],edi;1
 labelff69ebd73411a:;1
 mov edi,DWORD  [  ebp+     -560];1
 mov esi,DWORD  [  ebp+     -16];1
 lea esi,[  esi+     -2];1
 cmp edi,dword   esi;1
 jg near  labelff69ebd73411c;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [ edi];1
 mov DWORD  [  ebp+     -600],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 mov DWORD  [  ebp+     -592],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -588],edi;1
 mov edi,DWORD  [  ebp+     -16];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -580],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [ edi];1
 lea edi,[  edi+     2];1
 mov DWORD  [  ebp+     -648],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 mov DWORD  [  ebp+     -640],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -636],edi;1
 mov edi,DWORD  [  ebp+     -16];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -628],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [ edi];1
 inc DWORD edi;1
 mov DWORD  [  ebp+     -696],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 mov DWORD  [  ebp+     -688],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -684],edi;1
 mov edi,DWORD  [  ebp+     -16];1
 lea edi,[  edi+     -2];1
 mov DWORD  [  ebp+     -676],edi;1
 mov edi,DWORD  [  ebp+     -556];1
 imul  edi, [  ebp+     -540];1
 mov esi,DWORD  [  ebp+     -560];1
 lea edi,[  edi+esi];1
 mov esi,DWORD  [  ebp+     -552];1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     -560];1
 mov ebx,DWORD  [  ebp+     -556];1
 imul  ebx, [  ebp+     -588];1
 mov ecx,DWORD  [  ebp+     -600];1
 lea ecx,[  ecx+eax];1
 mov bl,byte  [  ebx+ecx];1
 mov ecx,DWORD  [  ebp+     -612];1
 mov bh,byte  [  ecx+eax];1
 push ax;1
 mov al,bh;1
 imul  bl;1
 shr ax,7;1
 mov bl,al;1
 pop ax;1
 mov eax,DWORD  [  ebp+     -556];1
 imul  eax, [  ebp+     -636];1
 mov ecx,DWORD  [  ebp+     -560];1
 lea eax,[  eax+ecx];1
 mov ecx,DWORD  [  ebp+     -648];1
 mov dl,byte  [  eax+ecx];1
 mov ecx,DWORD  [  ebp+     -660];1
 add ecx, [  ebp+     -560];1
 mov bh,byte  [ ecx];1
 push ax;1
 mov al,bh;1
 imul  dl;1
 shr ax,7;1
 mov dl,al;1
 pop ax;1
 add  bl,dl;1
 jno $+10;1
 jg $+6;1
 mov bl ,-128 ;1
 jng $+4;1
 mov bl,127;1
 ;1
 mov eax,DWORD  [  ebp+     -556];1
 imul  eax, [  ebp+     -684];1
 mov ecx,DWORD  [  ebp+     -560];1
 lea eax,[  eax+ecx];1
 mov ecx,DWORD  [  ebp+     -696];1
 mov dl,byte  [  eax+ecx];1
 mov ecx,DWORD  [  ebp+     -708];1
 add ecx, [  ebp+     -560];1
 mov bh,byte  [ ecx];1
 push ax;1
 mov al,bh;1
 imul  dl;1
 shr ax,7;1
 mov dl,al;1
 pop ax;1
 add  bl,dl;1
 jno $+10;1
 jg $+6;1
 mov bl ,-128 ;1
 jng $+4;1
 mov bl,127;1
 ;1
 mov BYTE  [  edi+esi],bl;1
 inc DWORD  [  ebp+     -560];1
 jmp  labelff69ebd73411a;1
 labelff69ebd73411c:;1
 inc DWORD  [  ebp+     -556];1
 jmp  labelff69ebd3cd112;1
 labelff69ebd3cd114:;1
; #320;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [ edi];1
 mov DWORD  [  ebp+     -768],edi;1
 mov DWORD  [  ebp+     -764],     0;1
 mov edi,DWORD  [  ebp+     -12];1
 mov DWORD  [  ebp+     -760],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -756],edi;1
 mov DWORD  [  ebp+     -752],     0;1
 mov DWORD  [  ebp+     -748],     0;1
 mov DWORD  [  ebp+     -772],     0;1
 labelff69ebebbe11e:;1
 mov edi,DWORD  [  ebp+     -772];1
 cmp edi,dword    [  ebp+     -12];1
 jg near  labelff69ebebbe120;1
 mov DWORD  [  ebp+     -812],     0;1
 mov DWORD  [  ebp+     -800],     0;1
 mov DWORD  [  ebp+     -796],     0;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [ edi];1
 mov DWORD  [  ebp+     -816],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 mov DWORD  [  ebp+     -808],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -804],edi;1
 mov DWORD  [  ebp+     -776],     0;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [ edi];1
 mov DWORD  [  ebp+     -816],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 mov DWORD  [  ebp+     -808],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -804],edi;1
 mov edi,DWORD  [  ebp+     -772];1
 imul  edi, [  ebp+     -756];1
 mov esi,DWORD  [  ebp+     -768];1
 mov ebx,DWORD  [  ebp+     -772];1
 imul  ebx, [  ebp+     -804];1
 mov eax,DWORD  [  ebp+     -816];1
 mov bl,byte  [  ebx+eax];1
 mov BYTE  [  edi+esi],bl;1
 inc DWORD  [  ebp+     -772];1
 jmp  labelff69ebebbe11e;1
 labelff69ebebbe120:;1
; #321;1
 mov edi,DWORD  [  ebp+     -16];1
 mov esi,DWORD  [  ebp+     8];1
 mov esi,DWORD  [ esi];1
 lea edi,[  edi+esi];1
 mov DWORD  [  ebp+     -864],edi;1
 mov DWORD  [  ebp+     -860],     0;1
 mov edi,DWORD  [  ebp+     -12];1
 mov DWORD  [  ebp+     -856],edi;1
 mov edi,DWORD  [  ebp+     8];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -852],edi;1
 mov DWORD  [  ebp+     -848],     0;1
 mov edi,DWORD  [  ebp+     -16];1
 sub edi, [  ebp+     -16];1
 mov DWORD  [  ebp+     -844],edi;1
 mov DWORD  [  ebp+     -868],     0;1
 labelff69ebec7c122:;1
 mov edi,DWORD  [  ebp+     -868];1
 cmp edi,dword    [  ebp+     -12];1
 jg near  labelff69ebec7c124;1
 mov DWORD  [  ebp+     -908],     0;1
 mov DWORD  [  ebp+     -896],     0;1
 mov edi,DWORD  [  ebp+     -16];1
 sub edi, [  ebp+     -16];1
 inc DWORD edi;1
 shr edi,      3;1
 lea edi,[   edi* 8+     -1];1
 mov DWORD  [  ebp+     -924],edi;1
 mov edi,DWORD  [  ebp+     -16];1
 mov esi,DWORD  [  ebp+     16];1
 mov esi,DWORD  [ esi];1
 lea edi,[  edi+esi];1
 mov DWORD  [  ebp+     -912],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 mov DWORD  [  ebp+     -904],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -900],edi;1
 mov edi,DWORD  [  ebp+     -16];1
 sub edi, [  ebp+     -16];1
 mov DWORD  [  ebp+     -892],edi;1
 mov DWORD  [  ebp+     -872],     0;1
 labelff69ebecea126:;1
 mov edi,DWORD  [  ebp+     -872];1
 cmp edi,dword    [  ebp+     -924];1
 jg near  labelff69ebecea128;1
 mov edi,DWORD  [  ebp+     -868];1
 imul  edi, [  ebp+     -852];1
 mov esi,DWORD  [  ebp+     -872];1
 mov ebx,DWORD  [  ebp+     -864];1
 lea esi,[  esi+ebx];1
 lea edi,[  edi+esi];1
 mov esi,DWORD  [  ebp+     -868];1
 imul  esi, [  ebp+     -900];1
 mov ebx,DWORD  [  ebp+     -872];1
 mov eax,DWORD  [  ebp+     -912];1
 lea ebx,[  ebx+eax];1
 movq MM4, [  esi+ebx];1
 movq  [ edi],MM4;1
 add  DWORD  [  ebp+     -872],     8;1
 jmp  labelff69ebecea126;1
 labelff69ebecea128:;1
 mov edi,DWORD  [  ebp+     -16];1
 sub edi, [  ebp+     -16];1
 inc DWORD edi;1
 shr edi,      3;1
 imul edi,DWORD edi,    8;1
 mov DWORD  [  ebp+     -872],edi;1
 labelff69ebedbd12a:;1
 mov edi,DWORD  [  ebp+     -872];1
 mov esi,DWORD  [  ebp+     -16];1
 sub esi, [  ebp+     -16];1
 cmp edi,dword   esi;1
 jg near  labelff69ebedbd12c;1
 mov edi,DWORD  [  ebp+     -16];1
 mov esi,DWORD  [  ebp+     16];1
 mov esi,DWORD  [ esi];1
 lea edi,[  edi+esi];1
 mov DWORD  [  ebp+     -912],edi;1
 mov edi,DWORD  [  ebp+     -12];1
 mov DWORD  [  ebp+     -904],edi;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     12];1
 mov DWORD  [  ebp+     -900],edi;1
 mov edi,DWORD  [  ebp+     -16];1
 sub edi, [  ebp+     -16];1
 mov DWORD  [  ebp+     -892],edi;1
 mov edi,DWORD  [  ebp+     -868];1
 imul  edi, [  ebp+     -852];1
 mov esi,DWORD  [  ebp+     -872];1
 lea edi,[  edi+esi];1
 mov esi,DWORD  [  ebp+     -864];1
 mov ebx,DWORD  [  ebp+     -868];1
 imul  ebx, [  ebp+     -900];1
 mov eax,DWORD  [  ebp+     -872];1
 lea ebx,[  ebx+eax];1
 mov eax,DWORD  [  ebp+     -912];1
 mov bl,byte  [  ebx+eax];1
 mov BYTE  [  edi+esi],bl;1
 inc DWORD  [  ebp+     -872];1
 jmp  labelff69ebedbd12a;1
 labelff69ebedbd12c:;1
 inc DWORD  [  ebp+     -868];1
 jmp  labelff69ebec7c122;1
 labelff69ebec7c124:;1
; #324;1
 labelff69eb9f309c:;1
spaceforconvpl3 equ 964;1
convpl3exit:;1
leave;1
 EMMS
  ret 0;4
section .text  ;0
; procedure generated by code generator class ilcg.tree.PentiumCG;0
labelff69eb88c51e:;0
;	 adjustcontrast;0
; entering a procedure at lexical level 1;0
 enter spaceforadjustcontrastl4-4*1,1;0
; #250;0
 push DWORD      12;0
 lea edi,[  ebp+     -12];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_getmem;0
%define defined_getmem ; defined by walker;0
EXTERN	 _getmem;0
%endif;0
 call _getmem; imported;4
 add esp, 8;0
 mov edi,DWORD  [  ebp+     -12];0
 mov DWORD  [  edi+     4],     0;0
 mov edi,DWORD  [  ebp+     -12];0
 mov esi,DWORD  [  ebp+     12];0
 mov esi,DWORD  [  esi+     32];0
 mov DWORD  [  edi+     8],esi;0
 push DWORD      1;0
 push DWORD      1;0
 lea edi,[  ebp+     -12];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_initvec;0
%define defined_initvec ; defined by walker;0
EXTERN	 _initvec;0
%endif;0
 call _initvec; imported;4
 add esp, 12;0
; #252;0
 mov edi,DWORD  [  ebp+     -12];0
 mov edi,DWORD  [  edi+     8];0
 mov DWORD  [  ebp+     -20],edi;0
 mov DWORD  [  ebp+     -16],     0;0
 labelff69ebef39132:;0
 mov edi,DWORD  [  ebp+     -16];0
 cmp edi,dword    [  ebp+     -20];0
 jg near  labelff69ebef39134;0
 mov edi,DWORD  [  ebp+     -12];0
 mov edi,DWORD  [ edi];0
 mov esi,DWORD  [  ebp+     -16];0
 fld dword  [  ebp+     8];2
 floadlit -1.0;2
 fcom st0,st1  ;2
push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jnb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 1.0;2
 fcom st0,st1  ;2
 push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 127.5;2
 fmulp st1;2
 floadlit -0.5;2
 faddp st1;2
  frndint;2
 sub esp,4;0
 fistp dword [esp];2
 pop  ebx;0
 mov dword[fttemp], ebx;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 pop  ebx;0
 mov BYTE  [  edi+esi],bl;0
 inc DWORD  [  ebp+     -16];0
 jmp  labelff69ebef39132;0
 labelff69ebef39134:;0
; #254;0
 push DWORD  [  ebp+     8];0
 call labelff68bae2be14;4
 add esp, 4;0
 fstp dword  [  ebp+     -36];2
 fld dword  [  ebp+     -36];2
 floadlit 1.0;2
 fxch;2
 fcompp ;2
push ax  ;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb near labelff69ebef93136;0
 mov edi,DWORD  [  ebp+     16];0
 mov edi,DWORD  [  edi+     8];0
 mov DWORD  [  ebp+     -96],edi;0
 mov DWORD  [  ebp+     -76],     0;0
 labelff69ebefa713a:;0
 mov edi,DWORD  [  ebp+     -76];0
 cmp edi,dword    [  ebp+     -96];0
 jg near  labelff69ebefa713c;0
 mov edi,DWORD  [  ebp+     16];0
 mov edi,DWORD  [  edi+     20];0
 mov DWORD  [  ebp+     -92],edi;0
 mov DWORD  [  ebp+     -80],     0;0
 labelff69ebefb113e:;0
 mov edi,DWORD  [  ebp+     -80];0
 cmp edi,dword    [  ebp+     -92];0
 jg near  labelff69ebefb1140;0
 mov edi,DWORD  [  ebp+     16];0
 mov edi,DWORD  [  edi+     32];0
 mov DWORD  [  ebp+     -88],edi;0
 mov DWORD  [  ebp+     -84],     0;0
 labelff69ebefbb142:;0
 mov edi,DWORD  [  ebp+     -84];0
 cmp edi,dword    [  ebp+     -88];0
 jg near  labelff69ebefbb144;0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     16];0
 mov edi,DWORD  [  ebp+     -76];0
 imul  edi, [  eax+     12];0
 mov esi,DWORD  [  ebp+     -80];0
 imul  esi, [  eax+     24];0
 mov ebx,DWORD  [  ebp+     -84];0
 lea esi,[  esi+ebx];0
 lea edi,[  edi+esi];0
 mov esi,DWORD  [  ebp+     16];0
 mov esi,DWORD  [ esi];0
; #substituting in eax with 3 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     12];0
 mov ebx,DWORD  [  ebp+     -80];0
 imul  ebx, [  eax+     24];0
 mov ecx,DWORD  [  ebp+     -84];0
 add ecx, [ eax];0
 lea ebx,[  ebx+ecx];0
 mov ecx,DWORD  [  ebp+     -76];0
 imul  ecx, [  eax+     12];0
 movsx ebx,BYTE    [  ebx+ecx];0
 mov dword[fttemp], ebx;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fmul DWORD  [  ebp+     8];2
 floadlit -1.0;2
 fcom st0,st1  ;2
push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jnb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 1.0;2
 fcom st0,st1  ;2
 push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 127.5;2
 fmulp st1;2
 floadlit -0.5;2
 faddp st1;2
  frndint;2
 sub esp,4;0
 fistp dword [esp];2
 pop  ebx;0
 mov dword[fttemp], ebx;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 pop  ebx;0
 mov BYTE  [  edi+esi],bl;0
 inc DWORD  [  ebp+     -84];0
 jmp  labelff69ebefbb142;0
 labelff69ebefbb144:;0
 inc DWORD  [  ebp+     -80];0
 jmp  labelff69ebefb113e;0
 labelff69ebefb1140:;0
 inc DWORD  [  ebp+     -76];0
 jmp  labelff69ebefa713a;0
 labelff69ebefa713c:;0
 jmp  labelff69ebef93138;0
 labelff69ebef93136:;0
 mov DWORD  [  ebp+     -40],     0;0
 labelff69ebf8bb146:;1
 mov edi,DWORD  [  ebp+     -40];1
 mov esi,DWORD  [  ebp+     16];1
 cmp edi,dword    [  esi+     8];1
 jg near  labelff69ebf8bb148;1
 mov DWORD  [  ebp+     -44],     0;1
 labelff69ebf8c514a:;1
 mov edi,DWORD  [  ebp+     -44];1
 mov esi,DWORD  [  ebp+     16];1
 cmp edi,dword    [  esi+     20];1
 jg near  labelff69ebf8cf14c;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     32];1
 inc DWORD edi;1
 shr edi,      3;1
 lea edi,[   edi* 8+     -1];1
 mov DWORD  [  ebp+     -64],edi;1
 mov DWORD  [  ebp+     -48],     0;1
 labelff69ebf8e314e:;1
 mov edi,DWORD  [  ebp+     -48];1
 cmp edi,dword    [  ebp+     -64];1
 jg near  labelff69ebf8e3150;1
; #substituting in eax with 3 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  ebp+     -44];1
 imul  edi, [  eax+     24];1
 mov esi,DWORD  [  ebp+     -48];1
 mov ebx,DWORD  [ eax];1
 lea esi,[  esi+ebx];1
 lea edi,[  edi+esi];1
 mov esi,DWORD  [  ebp+     -40];1
 imul  esi, [  eax+     12];1
 lea edi,[  edi+esi];1
; #substituting in ecx with 3 occurences and score of 6;1
 mov ecx,DWORD  [  ebp+     12];1
 mov esi,DWORD  [  ebp+     -44];1
 imul  esi, [  ecx+     24];1
 mov ebx,DWORD  [  ebp+     -40];1
 imul  ebx, [  ecx+     12];1
 add ebx, [ ecx];1
 add ebx, [  ebp+     -48];1
 movq MM4, [  esi+ebx];1
 mov esi,DWORD  [  ebp+     -12];1
 mov esi,DWORD  [ esi];1
 mov ebx,DWORD  [  ebp+     -48];1
 pxor MM7,MM7;1
 pxor MM5,MM5;1
 punpckhbw MM7, [  esi+ebx];1
 pxor MM6,MM6;1
 punpckhbw MM6,MM4;1
 punpcklbw MM5, [  esi+ebx];1
 pmulhw MM7,MM6;1
 psraw MM7,7;1
 pxor MM6,MM6;1
 punpcklbw MM6,MM4;1
 pmulhw MM5,MM6;1
 psraw MM5,7;1
 packsswb MM5,MM7;1
 movq MM4,MM5;1
 movq  [ edi],MM4;1
 add  DWORD  [  ebp+     -48],     8;1
 jmp  labelff69ebf8e314e;1
 labelff69ebf8e3150:;1
 mov edi,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  edi+     32];1
 inc DWORD edi;1
 shr edi,      3;1
 imul edi,DWORD edi,    8;1
 mov DWORD  [  ebp+     -48],edi;1
 labelff69ebfe17152:;1
 mov edi,DWORD  [  ebp+     -48];1
 mov esi,DWORD  [  ebp+     16];1
 cmp edi,dword    [  esi+     32];1
 jg near  labelff69ebfe17154;1
; #substituting in eax with 2 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     16];1
 mov edi,DWORD  [  ebp+     -40];1
 imul  edi, [  eax+     12];1
 mov esi,DWORD  [  ebp+     -44];1
 imul  esi, [  eax+     24];1
 mov ebx,DWORD  [  ebp+     -48];1
 lea esi,[  esi+ebx];1
 lea edi,[  edi+esi];1
 mov esi,DWORD  [  ebp+     16];1
 mov esi,DWORD  [ esi];1
; #substituting in eax with 3 occurences and score of 6;1
 mov eax,DWORD  [  ebp+     12];1
 mov ebx,DWORD  [  ebp+     -44];1
 imul  ebx, [  eax+     24];1
 mov ecx,DWORD  [  ebp+     -48];1
 add ecx, [ eax];1
 lea ebx,[  ebx+ecx];1
 mov ecx,DWORD  [  ebp+     -40];1
 imul  ecx, [  eax+     12];1
 mov bl,byte  [  ebx+ecx];1
 mov ecx,DWORD  [  ebp+     -12];1
 mov ecx,DWORD  [ ecx];1
 add ecx, [  ebp+     -48];1
 mov bh,byte  [ ecx];1
 push ax;1
 mov al,bh;1
 imul  bl;1
 shr ax,7;1
 mov bl,al;1
 pop ax;1
 mov BYTE  [  edi+esi],bl;1
 inc DWORD  [  ebp+     -48];1
 jmp  labelff69ebfe17152;1
 labelff69ebfe17154:;1
 inc DWORD  [  ebp+     -44];1
 jmp  labelff69ebf8c514a;1
 labelff69ebf8cf14c:;1
 inc DWORD  [  ebp+     -40];1
 jmp  labelff69ebf8bb146;1
 labelff69ebf8bb148:;1
 labelff69ebef93138:;1
; #256;1
 push DWORD      4;1
 lea edi,[  ebp+     -12];1
 mov dword[fttemp], edi;1
 EMMS
  fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_freemem;0
%define defined_freemem ; defined by walker;0
EXTERN	 _freemem;0
%endif;0
 call _freemem; imported;4
 add esp, 8;0
; #257;0
 labelff69eb8a2e6c:;0
spaceforadjustcontrastl4 equ 329;0
adjustcontrastl4exit:;0
leave;0
 ret 0;4
section .text  ;0
; procedure generated by code generator class ilcg.tree.PentiumCG;0
labelff69eb88c518:;0
;	 loadbmpfile;0
; entering a procedure at lexical level 1;0
 enter   0,1;0
 sub esp,spaceforloadbmpfilel5;0
; #201;0
 mov BYTE  [  ebp+     -5],  0;0
; #202;0
 lea edi,[  ebp+     8];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 lea edi,[  ebp+     -148];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_assign;0
%define defined_assign ; defined by walker;0
EXTERN	 _assign;0
%endif;0
 call _assign; imported;4
 add esp, 8;0
; #203;0
 lea edi,[  ebp+     -148];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_reset;0
%define defined_reset ; defined by walker;0
EXTERN	 _reset;0
%endif;0
 call _reset; imported;4
 add esp, 4;0
; #242;0
%ifndef defined_ioresult;0
%define defined_ioresult ; defined by walker;0
EXTERN	 _ioresult;0
%endif;0
 call _ioresult; imported;4
 mov DWORD  [  ebp+     -152],eax;0
  cmp DWORD  [  ebp+     -152],      0;0
 jnz near  labelff69ec032215e;0
; #210;0
 lea edi,[  ebp+     -148];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_filesize;0
%define defined_filesize ; defined by walker;0
EXTERN	 _filesize;0
%endif;0
 call _filesize; imported;4
 add esp, 4;0
 mov DWORD  [  ebp+     -220],eax;0
 mov edi,DWORD  [  ebp+     -220];0
 mov DWORD  [  ebp+     -116],edi;0
; #211;0
 mov DWORD  [  ebp+     -120],     54;0
; #212;0
 lea edi,[  ebp+     -144];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 push DWORD  [  ebp+     -120];0
 lea edi,[  ebp+     -108];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 lea edi,[  ebp+     -148];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_blockread;0
%define defined_blockread ; defined by walker;0
EXTERN	 _blockread;0
%endif;0
 call _blockread; imported;4
 add esp, 16;0
; #241;0
; #216;0
 push DWORD      36;0
 push DWORD  [  ebp+     168];0
%ifndef defined_getmem;0
%define defined_getmem ; defined by walker;0
EXTERN	 _getmem;0
%endif;0
 call _getmem; imported;4
 add esp, 8;0
 mov edi,DWORD  [  ebp+     168];0
 mov edi,DWORD  [ edi];0
 mov DWORD  [  edi+     4],     0;0
 mov edi,DWORD  [  ebp+     168];0
 mov edi,DWORD  [ edi];0
 mov DWORD  [  edi+     8],     2;0
 mov edi,DWORD  [  ebp+     168];0
 mov edi,DWORD  [ edi];0
 mov DWORD  [  edi+     16],     0;0
 mov edi,DWORD  [  ebp+     168];0
 mov edi,DWORD  [ edi];0
 mov esi,DWORD  [  ebp+     -86];0
 lea esi,[  esi+     -1];0
 mov DWORD  [  edi+     20],esi;0
 mov edi,DWORD  [  ebp+     168];0
 mov edi,DWORD  [ edi];0
 mov DWORD  [  edi+     28],     0;0
 mov edi,DWORD  [  ebp+     168];0
 mov edi,DWORD  [ edi];0
 mov esi,DWORD  [  ebp+     -90];0
 lea esi,[  esi+     -1];0
 mov DWORD  [  edi+     32],esi;0
 push DWORD      1;0
 push DWORD      3;0
 push DWORD  [  ebp+     168];0
%ifndef defined_initvec;0
%define defined_initvec ; defined by walker;0
EXTERN	 _initvec;0
%endif;0
 call _initvec; imported;4
 add esp, 12;0
; #217;0
 push DWORD      36;0
 lea edi,[  ebp+     -112];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_getmem;0
%define defined_getmem ; defined by walker;0
EXTERN	 _getmem;0
%endif;0
 call _getmem; imported;4
 add esp, 8;0
 mov edi,DWORD  [  ebp+     -112];0
 mov DWORD  [  edi+     4],     0;0
 mov edi,DWORD  [  ebp+     -112];0
 mov esi,DWORD  [  ebp+     -86];0
 lea esi,[  esi+     -1];0
 mov DWORD  [  edi+     8],esi;0
 mov edi,DWORD  [  ebp+     -112];0
 mov DWORD  [  edi+     16],     0;0
 mov edi,DWORD  [  ebp+     -112];0
 mov esi,DWORD  [  ebp+     -90];0
 lea esi,[  esi+     -1];0
 mov DWORD  [  edi+     20],esi;0
 mov edi,DWORD  [  ebp+     -112];0
 mov DWORD  [  edi+     28],     0;0
 mov edi,DWORD  [  ebp+     -112];0
 mov DWORD  [  edi+     32],     2;0
 push DWORD      1;0
 push DWORD      3;0
 lea edi,[  ebp+     -112];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_initvec;0
%define defined_initvec ; defined by walker;0
EXTERN	 _initvec;0
%endif;0
 call _initvec; imported;4
 add esp, 12;0
; #238;0
 mov bx,WORD  [  ebp+     -80];0
 movsx edi,   bx;0
  cmp DWORD edi,      8;0
 jz near  labelff69ec039b16e;0
 mov bx,WORD  [  ebp+     -80];0
 movsx edi,   bx;0
  cmp DWORD edi,      24;0
 jz near  labelff69ec03af172;0
 jmp  labelff69ec03af174;0
 labelff69ec03af172:;0
; #225;0
; #substituting in eax with 2 occurences and score of 10;0
 mov edi,DWORD  [  ebp+     168];0
 mov eax,DWORD  [ edi];0
 mov edi,DWORD  [  eax+     8];0
 inc DWORD edi;0
 mov esi,DWORD  [  eax+     32];0
 inc DWORD esi;0
 imul  edi,esi;RRD;0
 mov DWORD  [  ebp+     -116],edi;0
; #226;0
 mov edi,DWORD  [  ebp+     -116];0
 and edi,3;0
  cmp DWORD edi,      0;0
 jnz near  labelff69ec0409176;0
 jmp  labelff69ec0409178;0
 labelff69ec0409176:;0
 mov edi,DWORD  [  ebp+     -116];0
 lea edi,[  edi+     4];0
 mov esi,DWORD  [  ebp+     -116];0
 and esi,3;0
 sub edi,esi;RRD;0
 mov DWORD  [  ebp+     -116],edi;0
 labelff69ec0409178:;0
; #233;0
 mov edi,DWORD  [  ebp+     168];0
 mov edi,DWORD  [ edi];0
 mov edi,DWORD  [  edi+     20];0
 mov DWORD  [  ebp+     -244],edi;0
 mov DWORD  [  ebp+     -120],     0;0
 labelff69ec044f17a:;0
 mov edi,DWORD  [  ebp+     -120];0
 cmp edi,dword    [  ebp+     -244];0
 jg near  labelff69ec044f17c;0
; #230;0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     -112];0
 mov edi,DWORD  [  ebp+     -120];0
 imul  edi, [  eax+     12];0
 mov esi,DWORD  [ eax];0
 mov bh,byte  [  edi+esi];0
 mov BYTE  [  ebp+     -6],bh;0
; #232;0
 lea edi,[  ebp+     -144];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 push DWORD  [  ebp+     -116];0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     -112];0
 mov edi,DWORD  [  ebp+     -120];0
 imul  edi, [  eax+     12];0
 mov esi,DWORD  [ eax];0
 lea edi,[  edi+esi];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 lea edi,[  ebp+     -148];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_blockread;0
%define defined_blockread ; defined by walker;0
EXTERN	 _blockread;0
%endif;0
 call _blockread; imported;4
 add esp, 16;0
; #233;0
 inc DWORD  [  ebp+     -120];0
 jmp  labelff69ec044f17a;0
 labelff69ec044f17c:;0
; #235;0
 mov edi,DWORD  [  ebp+     168];0
 mov edi,DWORD  [ edi];0
 mov edi,DWORD  [  edi+     8];0
 mov DWORD  [  ebp+     -268],edi;0
 mov DWORD  [  ebp+     -248],     0;0
 labelff69ec04a9180:;0
 mov edi,DWORD  [  ebp+     -248];0
 cmp edi,dword    [  ebp+     -268];0
 jg near  labelff69ec04a9182;0
 mov edi,DWORD  [  ebp+     168];0
 mov edi,DWORD  [ edi];0
 mov edi,DWORD  [  edi+     20];0
 mov DWORD  [  ebp+     -264],edi;0
 mov DWORD  [  ebp+     -252],     0;0
 labelff69ec04b3184:;0
 mov edi,DWORD  [  ebp+     -252];0
 cmp edi,dword    [  ebp+     -264];0
 jg near  labelff69ec04b3186;0
 mov edi,DWORD  [  ebp+     168];0
 mov edi,DWORD  [ edi];0
 mov edi,DWORD  [  edi+     32];0
 mov DWORD  [  ebp+     -260],edi;0
 mov DWORD  [  ebp+     -256],     0;0
 labelff69ec04bd188:;0
 mov edi,DWORD  [  ebp+     -256];0
 cmp edi,dword    [  ebp+     -260];0
 jg near  labelff69ec04bd18a;0
; #substituting in eax with 3 occurences and score of 10;0
 mov edi,DWORD  [  ebp+     168];0
 mov eax,DWORD  [ edi];0
; #substituting in ecx with 3 occurences and score of 6;0
 mov ecx,DWORD  [  ebp+     -112];0
 mov edi,DWORD  [  ebp+     -256];0
 imul  edi, [  ecx+     24];0
 mov esi,DWORD  [  ebp+     -252];0
 imul  esi, [  ecx+     12];0
 mov ebx,DWORD  [ ecx];0
 lea esi,[  esi+ebx];0
 mov ebx,DWORD  [  ebp+     -248];0
 lea esi,[  esi+ebx];0
 movzx edi, BYTE   [  edi+esi];0
 lea ebx,[  edi+     -128];0
 mov BYTE  [  ebp+     -269],bl;0
 mov edi,DWORD  [  ebp+     -248];0
 imul  edi, [  eax+     12];0
 mov esi,DWORD  [  ebp+     -252];0
 imul  esi, [  eax+     24];0
 mov ebx,DWORD  [  ebp+     -256];0
 lea esi,[  esi+ebx];0
 lea edi,[  edi+esi];0
 mov esi,DWORD  [ eax];0
 mov bl,byte  [  ebp+     -269];0
 mov BYTE  [  edi+esi],bl;0
 inc DWORD  [  ebp+     -256];0
 jmp  labelff69ec04bd188;0
 labelff69ec04bd18a:;0
 inc DWORD  [  ebp+     -252];0
 jmp  labelff69ec04b3184;0
 labelff69ec04b3186:;0
 inc DWORD  [  ebp+     -248];0
 jmp  labelff69ec04a9180;0
 labelff69ec04a9182:;0
; #237;0
 mov BYTE  [  ebp+     -5],  -1;0
; #238;0
 labelff69ec03af174:;0
 jmp  labelff69ec039b170;0
 labelff69ec039b16e:;0
; #220;0
 mov BYTE  [  ebp+     -5],  0;0
; #221;0
 push DWORD      5;0
 push DWORD      12;0
 push DWORD  labelff69eb8a1064;0
 push DWORD  [   labelff68bae25a6+     -24];0
%ifndef defined_printstring;0
%define defined_printstring ; defined by walker;0
EXTERN	 _printstring;0
%endif;0
 call _printstring; imported;4
 add esp, 16;0
 push DWORD  [   labelff68bae25a6+     -24];0
%ifndef defined_println;0
%define defined_println ; defined by walker;0
EXTERN	 _println;0
%endif;0
 call _println; imported;4
 add esp, 4;0
; #222;0
 labelff69ec039b170:;0
; #239;0
 push DWORD      4;0
 lea edi,[  ebp+     -112];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_freemem;0
%define defined_freemem ; defined by walker;0
EXTERN	 _freemem;0
%endif;0
 call _freemem; imported;4
 add esp, 8;0
; #240;0
 lea edi,[  ebp+     -148];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_pasclose;0
%define defined_pasclose ; defined by walker;0
EXTERN	 _pasclose;0
%endif;0
 call _pasclose; imported;4
 add esp, 4;0
; #241;0
; #242;0
 jmp  labelff69ec0322160;0
 labelff69ec032215e:;0
; #204;0
 mov BYTE  [  ebp+     -5],  0;0
; #205;0
%ifndef defined_ioresult;0
%define defined_ioresult ; defined by walker;0
EXTERN	 _ioresult;0
%endif;0
 call _ioresult; imported;4
 mov DWORD  [  ebp+     -216],eax;0
 push DWORD      5;0
 push DWORD      12;0
 push DWORD  labelff69eb8a0662;0
 push DWORD  [   labelff68bae25a6+     -24];0
%ifndef defined_printstring;0
%define defined_printstring ; defined by walker;0
EXTERN	 _printstring;0
%endif;0
 call _printstring; imported;4
 add esp, 16;0
 push DWORD      5;0
 push DWORD      12;0
 lea edi,[  ebp+     8];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 push DWORD  [   labelff68bae25a6+     -24];0
%ifndef defined_printstring;0
%define defined_printstring ; defined by walker;0
EXTERN	 _printstring;0
%endif;0
 call _printstring; imported;4
 add esp, 16;0
 push DWORD      5;0
 push DWORD      12;0
 push DWORD  [  ebp+     -216];0
 push DWORD  [   labelff68bae25a6+     -24];0
%ifndef defined_printint;0
%define defined_printint ; defined by walker;0
EXTERN	 _printint;0
%endif;0
 call _printint; imported;4
 add esp, 16;0
 push DWORD  [   labelff68bae25a6+     -24];0
%ifndef defined_println;0
%define defined_println ; defined by walker;0
EXTERN	 _println;0
%endif;0
 call _println; imported;4
 add esp, 4;0
; #206;0
 labelff69ec0322160:;0
; #243;0
 labelff69eb89fc60:;0
 movsx eax,BYTE    [  ebp+     -5];0
spaceforloadbmpfilel5 equ 269;0
loadbmpfilel5exit:;0
leave;0
 ret 0;4
section .text  ;0
; procedure generated by code generator class ilcg.tree.PentiumCG;0
labelff69eb88c512:;0
;	 storebmpfile;0
; entering a procedure at lexical level 1;0
 enter   0,1;0
 sub esp,spaceforstorebmpfilel6;0
; #170;0
 lea edi,[  ebp+     8];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 lea edi,[  ebp+     -144];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_assign;0
%define defined_assign ; defined by walker;0
EXTERN	 _assign;0
%endif;0
 call _assign; imported;4
 add esp, 8;0
; #171;0
 lea edi,[  ebp+     -144];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_rewrite;0
%define defined_rewrite ; defined by walker;0
EXTERN	 _rewrite;0
%endif;0
 call _rewrite; imported;4
 add esp, 4;0
; #173;0
 push DWORD  [  ebp+     520];0
 lea edi,[  ebp+     -108];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 call labelff69eb88d93c;4
 add esp, 8;0
; #174;0
 lea edi,[  ebp+     -140];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 push DWORD      54;0
 lea edi,[  ebp+     -108];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 lea edi,[  ebp+     -144];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_blockwrite;0
%define defined_blockwrite ; defined by walker;0
EXTERN	 _blockwrite;0
%endif;0
 call _blockwrite; imported;4
 add esp, 16;0
; #175;0
 push DWORD      36;0
 lea edi,[  ebp+     -12];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_getmem;0
%define defined_getmem ; defined by walker;0
EXTERN	 _getmem;0
%endif;0
 call _getmem; imported;4
 add esp, 8;0
 mov edi,DWORD  [  ebp+     -12];0
 mov DWORD  [  edi+     4],     0;0
 mov edi,DWORD  [  ebp+     -12];0
 mov esi,DWORD  [  ebp+     520];0
 mov esi,DWORD  [  esi+     20];0
 mov DWORD  [  edi+     8],esi;0
 mov edi,DWORD  [  ebp+     -12];0
 mov DWORD  [  edi+     16],     0;0
 mov edi,DWORD  [  ebp+     -12];0
 mov esi,DWORD  [  ebp+     520];0
 mov esi,DWORD  [  esi+     32];0
 mov DWORD  [  edi+     20],esi;0
 mov edi,DWORD  [  ebp+     -12];0
 mov DWORD  [  edi+     28],     0;0
 mov edi,DWORD  [  ebp+     -12];0
 mov esi,DWORD  [  ebp+     520];0
 mov esi,DWORD  [  esi+     8];0
 mov DWORD  [  edi+     32],esi;0
 push DWORD      1;0
 push DWORD      3;0
 lea edi,[  ebp+     -12];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_initvec;0
%define defined_initvec ; defined by walker;0
EXTERN	 _initvec;0
%endif;0
 call _initvec; imported;4
 add esp, 12;0
; #179;0
 mov edi,DWORD  [  ebp+     -12];0
 mov edi,DWORD  [  edi+     8];0
 mov esi,DWORD  [  ebp+     520];0
 cmp edi,dword    [  esi+     20];0
 jg near  labelff69ec07ac1a8;0
 jmp  labelff69ec07ac1aa;0
 labelff69ec07ac1a8:;0
 push DWORD      179;0
 mov edi,DWORD  [  ebp+     -12];0
 push DWORD  [  edi+     8];0
 push DWORD      0;0
 mov edi,DWORD  [  ebp+     520];0
 push DWORD  [  edi+     20];0
 call labelff68bae2dcda;4
 add esp, 16;0
 labelff69ec07ac1aa:;0
 mov edi,DWORD  [  ebp+     -12];0
 mov edi,DWORD  [  edi+     8];0
 mov DWORD  [  ebp+     -168],edi;0
 mov DWORD  [  ebp+     -148],     0;0
 labelff69ec07c01ac:;0
 mov edi,DWORD  [  ebp+     -148];0
 cmp edi,dword    [  ebp+     -168];0
 jg near  labelff69ec07c01ae;0
 mov edi,DWORD  [  ebp+     -12];0
 mov edi,DWORD  [  edi+     20];0
 mov esi,DWORD  [  ebp+     520];0
 cmp edi,dword    [  esi+     32];0
 jg near  labelff69ec07ca1b0;0
 jmp  labelff69ec07ca1b2;0
 labelff69ec07ca1b0:;0
 push DWORD      179;0
 mov edi,DWORD  [  ebp+     -12];0
 push DWORD  [  edi+     20];0
 push DWORD      0;0
 mov edi,DWORD  [  ebp+     520];0
 push DWORD  [  edi+     32];0
 call labelff68bae2dcda;4
 add esp, 16;0
 labelff69ec07ca1b2:;0
 mov edi,DWORD  [  ebp+     -12];0
 mov edi,DWORD  [  edi+     20];0
 mov DWORD  [  ebp+     -164],edi;0
 mov DWORD  [  ebp+     -152],     0;0
 labelff69ec07e81b4:;0
 mov edi,DWORD  [  ebp+     -152];0
 cmp edi,dword    [  ebp+     -164];0
 jg near  labelff69ec07e81b6;0
 mov edi,DWORD  [  ebp+     -12];0
 mov edi,DWORD  [  edi+     32];0
 mov esi,DWORD  [  ebp+     520];0
 cmp edi,dword    [  esi+     8];0
 jg near  labelff69ec07f21b8;0
 jmp  labelff69ec07f21ba;0
 labelff69ec07f21b8:;0
 push DWORD      179;0
 mov edi,DWORD  [  ebp+     -12];0
 push DWORD  [  edi+     32];0
 push DWORD      0;0
 mov edi,DWORD  [  ebp+     520];0
 push DWORD  [  edi+     8];0
 call labelff68bae2dcda;4
 add esp, 16;0
 labelff69ec07f21ba:;0
 mov edi,DWORD  [  ebp+     -12];0
 mov edi,DWORD  [  edi+     32];0
 mov DWORD  [  ebp+     -160],edi;0
 mov DWORD  [  ebp+     -156],     0;0
 labelff69ec07fc1bc:;0
 mov edi,DWORD  [  ebp+     -156];0
 cmp edi,dword    [  ebp+     -160];0
 jg near  labelff69ec07fc1be;0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     -12];0
 mov edi,DWORD  [  ebp+     -148];0
 imul  edi, [  eax+     12];0
 mov esi,DWORD  [  ebp+     -152];0
 imul  esi, [  eax+     24];0
 mov ebx,DWORD  [  ebp+     -156];0
 lea esi,[  esi+ebx];0
 lea edi,[  edi+esi];0
 mov esi,DWORD  [  ebp+     -12];0
 mov esi,DWORD  [ esi];0
; #substituting in eax with 3 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     520];0
 mov ebx,DWORD  [  ebp+     -148];0
 imul  ebx, [  eax+     24];0
 mov ecx,DWORD  [  ebp+     -152];0
 add ecx, [ eax];0
 lea ebx,[  ebx+ecx];0
 mov ecx,DWORD  [  ebp+     -156];0
 imul  ecx, [  eax+     12];0
 mov bl,byte  [  ebx+ecx];0
 add  BYTE bl,  -128;0
 mov BYTE  [  edi+esi],bl;0
 inc DWORD  [  ebp+     -156];0
 jmp  labelff69ec07fc1bc;0
 labelff69ec07fc1be:;0
 inc DWORD  [  ebp+     -152];0
 jmp  labelff69ec07e81b4;0
 labelff69ec07e81b6:;0
 inc DWORD  [  ebp+     -148];0
 jmp  labelff69ec07c01ac;0
 labelff69ec07c01ae:;0
; #183;0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     520];0
 mov edi,DWORD  [  eax+     8];0
 inc DWORD edi;0
 mov esi,DWORD  [  eax+     32];0
 inc DWORD esi;0
 imul  edi,esi;RRD;0
 mov DWORD  [  ebp+     -112],edi;0
; #184;0
 mov edi,DWORD  [  ebp+     -112];0
 and edi,3;0
  cmp DWORD edi,      0;0
 jnz near  labelff69ec0a5f1c0;0
 jmp  labelff69ec0a5f1c2;0
 labelff69ec0a5f1c0:;0
 mov edi,DWORD  [  ebp+     -112];0
 lea edi,[  edi+     4];0
 mov esi,DWORD  [  ebp+     -112];0
 and esi,3;0
 sub edi,esi;RRD;0
 mov DWORD  [  ebp+     -112],edi;0
 labelff69ec0a5f1c2:;0
; #187;0
 mov edi,DWORD  [  ebp+     520];0
 mov edi,DWORD  [  edi+     20];0
 mov DWORD  [  ebp+     -172],edi;0
 mov DWORD  [  ebp+     -116],     0;0
 labelff69ec0a871c4:;0
 mov edi,DWORD  [  ebp+     -116];0
 cmp edi,dword    [  ebp+     -172];0
 jg near  labelff69ec0a871c6;0
 mov edi,DWORD  [  ebp+     -12];0
 mov edi,DWORD  [  edi+     8];0
 cmp edi,dword    [  ebp+     -116];0
 jl near  labelff69ec0a911c8;0
 jmp  labelff69ec0a911ca;0
 labelff69ec0a911c8:;0
 push DWORD      187;0
 mov edi,DWORD  [  ebp+     -12];0
 push DWORD  [  edi+     8];0
 mov edi,DWORD  [  ebp+     -12];0
 push DWORD  [  edi+     8];0
 push DWORD  [  ebp+     -116];0
 call labelff68bae2c846;4
 add esp, 16;0
 labelff69ec0a911ca:;0
 xor edi,edi;0
 mov esi,DWORD  [  ebp+     -12];0
 cmp edi,dword    [  esi+     20];0
 jg near  labelff69ec0aa51cc;0
 jmp  labelff69ec0aa51ce;0
 labelff69ec0aa51cc:;0
 push DWORD      187;0
 push DWORD      201;0
 call labelff68bae2fa230;4
 add esp, 8;0
 labelff69ec0aa51ce:;0
 xor edi,edi;0
 mov esi,DWORD  [  ebp+     -12];0
 cmp edi,dword    [  esi+     32];0
 jg near  labelff69ec0aaf1d0;0
 jmp  labelff69ec0aaf1d2;0
 labelff69ec0aaf1d0:;0
 push DWORD      187;0
 push DWORD      201;0
 call labelff68bae2fa230;4
 add esp, 8;0
 labelff69ec0aaf1d2:;0
 lea edi,[  ebp+     -140];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 push DWORD  [  ebp+     -112];0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     -12];0
 mov edi,DWORD  [  ebp+     -116];0
 imul  edi, [  eax+     12];0
 mov esi,DWORD  [ eax];0
 lea edi,[  edi+esi];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 lea edi,[  ebp+     -144];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_blockwrite;0
%define defined_blockwrite ; defined by walker;0
EXTERN	 _blockwrite;0
%endif;0
 call _blockwrite; imported;4
 add esp, 16;0
 inc DWORD  [  ebp+     -116];0
 jmp  labelff69ec0a871c4;0
 labelff69ec0a871c6:;0
; #190;0
 push DWORD      4;0
 lea edi,[  ebp+     -12];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_freemem;0
%define defined_freemem ; defined by walker;0
EXTERN	 _freemem;0
%endif;0
 call _freemem; imported;4
 add esp, 8;0
; #191;0
 lea edi,[  ebp+     -144];0
 mov dword[fttemp], edi;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
%ifndef defined_pasclose;0
%define defined_pasclose ; defined by walker;0
EXTERN	 _pasclose;0
%endif;0
 call _pasclose; imported;4
 add esp, 4;0
; #193;0
 labelff69eb89b658:;0
spaceforstorebmpfilel6 equ 173;0
storebmpfilel6exit:;0
leave;0
 ret 0;4
section .text  ;0
; procedure generated by code generator class ilcg.tree.PentiumCG;0
labelff69eb88d93c:;0
;	 initbmpheader;0
; entering a procedure at lexical level 1;0
 enter spaceforinitbmpheaderl7-4*1,1;0
; #110;0
 mov edi,DWORD  [  ebp+     8];0
 mov BYTE  [ edi],  66;0
; #111;0
 mov edi,DWORD  [  ebp+     8];0
 mov BYTE  [  edi+     1],  77;0
; #115;0
; #substituting in eax with 3 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     12];0
 mov edi,DWORD  [  ebp+     8];0
 mov esi,DWORD  [  eax+     32];0
 inc DWORD esi;0
 mov ebx,DWORD  [  eax+     8];0
 inc DWORD ebx;0
 imul  esi,ebx;RRD;0
 mov ebx,DWORD  [  eax+     20];0
 inc DWORD ebx;0
 imul  esi,ebx;RRD;0
 lea esi,[  esi+     54];0
 mov DWORD  [  edi+     2],esi;0
; #116;0
 mov DWORD  [  ebp+     -8],     0;0
 mov edi,DWORD  [  ebp+     8];0
 mov esi,DWORD  [  ebp+     -8];0
 mov BYTE  [  edi+esi +     6],  0;0
 inc DWORD  [  ebp+     -8];0
 mov edi,DWORD  [  ebp+     8];0
 mov esi,DWORD  [  ebp+     -8];0
 mov BYTE  [  edi+esi +     6],  0;0
 inc DWORD  [  ebp+     -8];0
 mov edi,DWORD  [  ebp+     8];0
 mov esi,DWORD  [  ebp+     -8];0
 mov BYTE  [  edi+esi +     6],  0;0
 inc DWORD  [  ebp+     -8];0
 mov edi,DWORD  [  ebp+     8];0
 mov esi,DWORD  [  ebp+     -8];0
 mov BYTE  [  edi+esi +     6],  0;0
; #117;0
 mov edi,DWORD  [  ebp+     8];0
 mov DWORD  [  edi+     10],     54;0
; #157;0
; #147;0
 mov edi,DWORD  [  ebp+     8];0
 mov DWORD  [  edi+     14],     40;0
; #148;0
 mov edi,DWORD  [  ebp+     8];0
 mov esi,DWORD  [  ebp+     12];0
 mov esi,DWORD  [  esi+     32];0
 inc DWORD esi;0
 mov DWORD  [  edi+     18],esi;0
; #149;0
 mov edi,DWORD  [  ebp+     8];0
 mov esi,DWORD  [  ebp+     12];0
 mov esi,DWORD  [  esi+     20];0
 inc DWORD esi;0
 mov DWORD  [  edi+     22],esi;0
; #150;0
 mov edi,DWORD  [  ebp+     8];0
 mov WORD  [  edi+     26],   1;0
; #151;0
 mov edi,DWORD  [  ebp+     8];0
 mov esi,DWORD  [  ebp+     12];0
 mov esi,DWORD  [  esi+     8];0
 inc DWORD esi;0
 imul ebx,DWORD esi,    8;0
 mov WORD  [  edi+     28],bx;0
; #152;0
 mov edi,DWORD  [  ebp+     8];0
 mov DWORD  [  edi+     30],     0;0
; #153;0
 mov edi,DWORD  [  ebp+     8];0
 mov DWORD  [  edi+     38],     3780;0
; #154;0
 mov edi,DWORD  [  ebp+     8];0
 mov DWORD  [  edi+     42],     3780;0
; #155;0
 mov edi,DWORD  [  ebp+     8];0
 mov DWORD  [  edi+     46],     0;0
; #156;0
 mov edi,DWORD  [  ebp+     8];0
 mov DWORD  [  edi+     50],     0;0
; #157;0
; #160;0
 labelff69eb88d940:;0
spaceforinitbmpheaderl7 equ 28;0
initbmpheaderl7exit:;0
leave;0
 ret 0;4
section .text  ;0
; procedure generated by code generator class ilcg.tree.PentiumCG;0
labelff69ebb03eae:;0
;	 unit$bmp;0
; entering a unit at lexical level 0;0
unit$bmp:;0
 enter  0,0;0
 call unit$system;4
cmp byte[unit$bmpready],1;0
 jnz unit$bmpinit;0
 jmp unit$bmpl8exit;0
unit$bmpinit:mov byte[unit$bmpready],1;0
; #355;0
 labelff69eb88cf38:;0
spaceforunit$bmpl8 equ 0;0
unit$bmpl8exit:;0
leave;0
 ret 0;4
	SECTION .bss;0
	alignb 16;0
resb spaceforunit$bmpl8;0
	alignb 16;0
 labelff69eb8373a:;0
	SECTION .data;0
unit$bmpready dd 0;0
 labelff69eb9f308c:;0
 dd 0.00392156862745098;0
 labelff69eb9f308a:;0
 dd 0.00392156862745098;0
 labelff69eb9f3088:;0
 dd 0.00392156862745098;0
 labelff69eb9f3086:;0
 dd 0.00392156862745098;0
 labelff69eb9f3084:;0
 dd 0.00392156862745098;0
 labelff69eb9f3082:;0
 dd 0.00392156862745098;0
 labelff69eb9f3080:;0
 dd 0.00392156862745098;0
 labelff69eb9f307e:;0
 dd 0.00392156862745098;0
 labelff69eb9f307c:;0
 dd 0.00784313725490196;0
 labelff69eb9f307a:;0
 dd 0.00784313725490196;0
 labelff69eb9f3078:;0
 dd 0.00784313725490196;0
 labelff69eb9f3076:;0
 dd 0.00784313725490196;0
 labelff69eb9f3074:;0
 dd 0.00784313725490196;0
 labelff69eb9f3072:;0
 dd 0.00784313725490196;0
 labelff69eb9f3070:;0
 dd 0.00784313725490196;0
 labelff69eb9f306e:;0
 dd 0.00784313725490196;0
 labelff69eb890250:;0
 db  0;0
 labelff69eb89024e:;0
 db  0;0
 labelff69eb89024c:;0
 db  0;0
 labelff69eb89024a:;0
 db  0;0
 labelff69eb890248:;0
 db  0;0
 labelff69eb890246:;0
 db  0;0
 labelff69eb890244:;0
 db  0;0
 labelff69eb88f842:;0
 db  0;0
 labelff69eb8a0662:;0
 dw   10;0
 dw   99;0
 dw   97;0
 dw   110;0
 dw   116;0
 dw   32;0
 dw   111;0
 dw   112;0
 dw   101;0
 dw   110;0
 dw   32;0
 labelff69eb8a1064:;0
 dw   30;0
 dw   32;0
 dw   56;0
 dw   32;0
 dw   98;0
 dw   105;0
 dw   116;0
 dw   32;0
 dw   98;0
 dw   109;0
 dw   112;0
 dw   32;0
 dw   102;0
 dw   105;0
 dw   108;0
 dw   101;0
 dw   115;0
 dw   32;0
 dw   110;0
 dw   111;0
 dw   116;0
 dw   32;0
 dw   115;0
 dw   117;0
 dw   112;0
 dw   112;0
 dw   111;0
 dw   114;0
 dw   116;0
 dw   101;0
 dw   100;0
%include "c:\src\VectorPascal\mmpc/system.asm"
%endif
