.include "/home/wpc/vp/mmpc/macros.s"
.section .text  
; #procedure generated by code generator class ilcg.tree.gnuP4CG
	.global Pmain
label12c7901935a4c0:
Pmain:
# entering a procedure at lexical level 0
	enter $spaceforPmainl9-4*0,$0
	push %ebx
	push %esi
	push %edi
	push %ebx
	push %esi
	push %edi
 call unit$system
 call unit$bmp
cmpb $1,Pmainready
 jnz Pmaininit
 jmp Pmainl9exit
Pmaininit:movb $1, Pmainready
; #7
 movsbl     PmainBase+    -1,   %eax
  sub $8, %esp
  movl %eax, (%esp)
  fildl (%esp)
  add $8, %esp 
 jmp 0f
1:.double  0.00784313725490196
0:fldl 1b
 fmulp
 jmp 0f
1:.double  0.00392156862745098
0:fldl 1b
 faddp
 jmp 0f
1:.double  0.4
0:fldl 1b
 fmulp
 jmp 0f
1:.double  -1.0
0:fldl 1b
 fcom %st(1)  
pushw %ax
 fstsw %ax
 sahf
 popw %ax
 jnb 0f 
 fxch 
fstp %st(1)
0:
 jmp 0f
1:.double  1.0
0:fldl 1b
 fcom %st(1)  
 pushw %ax
 fstsw %ax
 sahf
 pop %ax
 jb 0f 
 fxch 
fstp %st(1)
0:
 jmp 0f
1:.double  127.5
0:fldl 1b
 fmulp
 jmp 0f
1:.double  -0.5
0:fldl 1b
 faddp
  frndint
 subl $4, %esp
 fistpl  (%esp)
 popl  %eax
#pushl %eax
 #popl  %ebx  ---> 
 mov  %eax,  %ebx
 movb %bl,    PmainBase+    -1
; #9
 pushl $  PmainBase+    -28
 addl  $     -160,%esp
 movl  $    0,     PmainBase+    -64
 label12c7901936f4c5:
  cmpl  $    79,      PmainBase+    -64
 jg   label12c7901936f4c7
 movl  $    0,     PmainBase+    -68
 label12c7901939a4c9:
  cmpl  $    7,      PmainBase+    -68
 jg   label12c7901939a4cb
 imull $    2,     PmainBase+    -68,%eax
 addl %esp,%eax
 movl     PmainBase+    -64,%edi
 imull $    2,     PmainBase+    -64,%ebx
 movl     PmainBase+    -68,%esi
 movw     label12c790193574ba(%ebx,%esi, 2),%bx
 movw %bx,   0(%eax,%edi, 2)#STOREWR
 incl     PmainBase+    -68
 jmp  label12c7901939a4c9
 label12c7901939a4cb:
 addl  $     8,    PmainBase+    -64
 jmp  label12c7901936f4c5
 label12c7901936f4c7:
 call label12c7901713616
 add  $164,%esp
 movb %al,    PmainBase+    -33
 movb     PmainBase+    -33,%bl
 movb %bl,    PmainBase+    -21
; #15
 movb     PmainBase+    -21,%bl
 test %bl,%bl
 jnz label12c790193b64cd
 pushl $ label12c7901935a4be
.ifndef definedlength
definedlength=1
.extern 	 length
.endif
 call length#imported
 add  $4,%esp
 movl %eax,    PmainBase+    -60#STORER
 pushl $     5
 pushl     PmainBase+    -60
 pushl $ label12c7901935a4be
 pushl     unit$system$base+    -24
.ifndef definedprintstring
definedprintstring=1
.extern 	 printstring
.endif
 call printstring#imported
 add  $16,%esp
 pushl     unit$system$base+    -24
.ifndef definedprintln
definedprintln=1
.extern 	 println
.endif
 call println#imported
 add  $4,%esp
 jmp  label12c790193b64cf
 label12c790193b64cd:
; #12
 pushl     PmainBase+    -28
 call label12c7901713828
 add  $4,%esp
; #13
 pushl     PmainBase+    -28
 addl  $     -1024,%esp
 movl  $    0,     PmainBase+    -72
 label12c790193bd4d7:
  cmpl  $    511,      PmainBase+    -72
 jg   label12c790193bd4d9
 movl  $    0,     PmainBase+    -76
 label12c790193c64db:
  cmpl  $    7,      PmainBase+    -76
 jg   label12c790193c64dd
 imull $    2,     PmainBase+    -76,%eax
 addl %esp,%eax
 movl     PmainBase+    -72,%edi
 imull $    2,     PmainBase+    -72,%ebx
 movl     PmainBase+    -76,%esi
 movw     label12c7901935a4bc(%ebx,%esi, 2),%bx
 movw %bx,   0(%eax,%edi, 2)#STOREWR
 incl     PmainBase+    -76
 jmp  label12c790193c64db
 label12c790193c64dd:
 addl  $     8,    PmainBase+    -72
 jmp  label12c790193bd4d7
 label12c790193bd4d9:
 call label12c7901713510
 add  $1028,%esp
; #14
 label12c790193b64cf:
; #17
 label12c790193574b8:
spaceforPmainl9 = 76
Pmainl9exit:
	pop %edi
	pop %esi
	pop %ebx
	pop %edi
	pop %esi
	pop %ebx
	leave
 	ret $0
	.section .bss
	.align 4
	.space 76
	.align 4
PmainBase:
	.section .data
Pmainready: .byte  0
 label12c790193574ba:
 .short   9
 .short   103
 .short   114
 .short   101
 .short   121
 .short   49
 .short   46
 .short   98
 .short   109
 .short   112
 label12c7901935a4bc:
 .short   12
 .short   103
 .short   114
 .short   101
 .short   121
 .short   98
 .short   108
 .short   117
 .short   114
 .short   46
 .short   98
 .short   109
 .short   112
 label12c7901935a4be:
 .short   6
 .short   102
 .short   97
 .short   105
 .short   108
 .short   101
 .short   100
; #invocations per line output =4.972727272727273
; #invocations per source statement =109.4
; #assembler lines per source statement =22.2
.include "/home/wpc/vp/mmpc/systemgnuP4.asm"
.include "bmpgnuP4.asm"
.section .data
