%ifndef vq
%define vq ; defined by walker;0
section .text  ;0
; procedure generated by code generator class ilcg.tree.PentiumCG;0
labelff69d6ea7a10:;0
;	 encode;0
; entering a procedure at lexical level 1;0
 enter   0,1;0
 sub esp,spaceforencodel0;0
; #29;0
 mov DWORD  [  ebp+     -152],     0;0
 labelff69d6eb8920:;0
  cmp DWORD  [  ebp+     -152],      15;0
 jg near  labelff69d6eb8922;0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     -152];0
 mov esi,DWORD  [  ebp+     8];0
 movsx esi,BYTE    [  esi+eax];0
 mov dword[fttemp], esi;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  ebp+ eax* 4+     -128];2
 inc DWORD  [  ebp+     -152];0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     -152];0
 mov esi,DWORD  [  ebp+     8];0
 movsx esi,BYTE    [  esi+eax];0
 mov dword[fttemp], esi;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  ebp+ eax* 4+     -128];2
 inc DWORD  [  ebp+     -152];0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     -152];0
 mov esi,DWORD  [  ebp+     8];0
 movsx esi,BYTE    [  esi+eax];0
 mov dword[fttemp], esi;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  ebp+ eax* 4+     -128];2
 inc DWORD  [  ebp+     -152];0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [  ebp+     -152];0
 mov esi,DWORD  [  ebp+     8];0
 movsx esi,BYTE    [  esi+eax];0
 mov dword[fttemp], esi;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  ebp+ eax* 4+     -128];2
 inc DWORD  [  ebp+     -152];0
 jmp  labelff69d6eb8920;0
 labelff69d6eb8922:;0
; #30;0
 mov DWORD  [  ebp+     -144],     0;0
; #30;0
 floadlit 32.0;2
 fstp dword  [  ebp+     -136];2
; #39;0
 mov DWORD  [  ebp+     -140],     0;0
 labelff69d6ed7e24:;0
  cmp DWORD  [  ebp+     -140],      255;0
 jg near  labelff69d6ed7e26;0
; #33;0
 floadlit 0.0;2
 fstp dword  [  ebp+     -168];2
 mov DWORD  [  ebp+     -164],     15;0
 labelff69d6ed9c28:;0
  cmp DWORD  [  ebp+     -164],      0;0
 jl near  labelff69d6ed9c2a;0
 mov esi,DWORD  [  ebp+     -164];0
 fld dword  [  ebp+ esi* 4+     -128];2
 imul esi,DWORD  [  ebp+     -140],    64;0
 mov ebx,DWORD  [  ebp+     -164];0
 fsub DWORD  [  esi+ ebx* 4+  labelff69d6e5008+     -16384];2
 mov esi,DWORD  [  ebp+     -164];0
 fld dword  [  ebp+ esi* 4+     -128];2
 imul esi,DWORD  [  ebp+     -140],    64;0
 mov ebx,DWORD  [  ebp+     -164];0
 fsub DWORD  [  esi+ ebx* 4+  labelff69d6e5008+     -16384];2
 fmulp st1;2
 fadd DWORD  [  ebp+     -168];2
 fstp dword  [  ebp+     -168];2
 add  DWORD  [  ebp+     -164],     -1;0
 mov esi,DWORD  [  ebp+     -164];0
 fld dword  [  ebp+ esi* 4+     -128];2
 imul esi,DWORD  [  ebp+     -140],    64;0
 mov ebx,DWORD  [  ebp+     -164];0
 fsub DWORD  [  esi+ ebx* 4+  labelff69d6e5008+     -16384];2
 mov esi,DWORD  [  ebp+     -164];0
 fld dword  [  ebp+ esi* 4+     -128];2
 imul esi,DWORD  [  ebp+     -140],    64;0
 mov ebx,DWORD  [  ebp+     -164];0
 fsub DWORD  [  esi+ ebx* 4+  labelff69d6e5008+     -16384];2
 fmulp st1;2
 fadd DWORD  [  ebp+     -168];2
 fstp dword  [  ebp+     -168];2
 add  DWORD  [  ebp+     -164],     -1;0
 mov esi,DWORD  [  ebp+     -164];0
 fld dword  [  ebp+ esi* 4+     -128];2
 imul esi,DWORD  [  ebp+     -140],    64;0
 mov ebx,DWORD  [  ebp+     -164];0
 fsub DWORD  [  esi+ ebx* 4+  labelff69d6e5008+     -16384];2
 mov esi,DWORD  [  ebp+     -164];0
 fld dword  [  ebp+ esi* 4+     -128];2
 imul esi,DWORD  [  ebp+     -140],    64;0
 mov ebx,DWORD  [  ebp+     -164];0
 fsub DWORD  [  esi+ ebx* 4+  labelff69d6e5008+     -16384];2
 fmulp st1;2
 fadd DWORD  [  ebp+     -168];2
 fstp dword  [  ebp+     -168];2
 add  DWORD  [  ebp+     -164],     -1;0
 mov esi,DWORD  [  ebp+     -164];0
 fld dword  [  ebp+ esi* 4+     -128];2
 imul esi,DWORD  [  ebp+     -140],    64;0
 mov ebx,DWORD  [  ebp+     -164];0
 fsub DWORD  [  esi+ ebx* 4+  labelff69d6e5008+     -16384];2
 mov esi,DWORD  [  ebp+     -164];0
 fld dword  [  ebp+ esi* 4+     -128];2
 imul esi,DWORD  [  ebp+     -140],    64;0
 mov ebx,DWORD  [  ebp+     -164];0
 fsub DWORD  [  esi+ ebx* 4+  labelff69d6e5008+     -16384];2
 fmulp st1;2
 fadd DWORD  [  ebp+     -168];2
 fstp dword  [  ebp+     -168];2
 add  DWORD  [  ebp+     -164],     -1;0
 jmp  labelff69d6ed9c28;0
 labelff69d6ed9c2a:;0
 fld dword  [  ebp+     -168];2
 fstp dword  [  ebp+     -172];2
 fld dword  [  ebp+     -172];2
 fstp dword  [  ebp+     -132];2
; #39;0
 fld dword  [  ebp+     -132];2
 fcomp dword  [  ebp+     -136] ;2
push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb near  labelff69d6eeb42c;0
 jmp  labelff69d6eeb42e;0
 labelff69d6eeb42c:;0
; #36;0
 mov edi,DWORD  [  ebp+     -140];0
 mov DWORD  [  ebp+     -144],edi;0
; #37;0
 fld dword  [  ebp+     -132];2
 fstp dword  [  ebp+     -136];2
; #38;0
 labelff69d6eeb42e:;0
 inc DWORD  [  ebp+     -140];0
 jmp  labelff69d6ed7e24;0
 labelff69d6ed7e26:;0
; #40;0
 mov eax,DWORD  [  ebp+     -144];0
 mov BYTE  [  ebp+     -5],al;0
; #41;0
 labelff69d6ea841a:;0
 movzx eax, BYTE   [  ebp+     -5];0
spaceforencodel0 equ 172;0
encodel0exit:;0
leave;0
 ret 0;4
section .text  ;0
; procedure generated by code generator class ilcg.tree.PentiumCG;0
labelff69d6eb391c:;0
;	 unit$vq;0
; entering a unit at lexical level 0;0
unit$vq:;0
 enter  0,0;0
 call unit$system;4
cmp byte[unit$vqready],1;0
 jnz unit$vqinit;0
 jmp unit$vql1exit;0
unit$vqinit:mov byte[unit$vqready],1;0
; #43;0
 mov WORD  [   labelff69d6e5008+     -20500],   256;0
; #44;0
 mov WORD  [   labelff69d6e5008+     -20498],   17;0
; #45;0
 mov DWORD  [   labelff69d6e5008+     -20504],     0;0
 labelff69d6eee630:;0
  cmp DWORD  [   labelff69d6e5008+     -20504],      255;0
 jg near  labelff69d6eee632;0
 mov DWORD  [   labelff69d6e5008+     -20508],     0;0
 labelff69d6eef034:;0
  cmp DWORD  [   labelff69d6e5008+     -20508],      15;0
 jg near  labelff69d6eef036;0
 imul esi,DWORD  [   labelff69d6e5008+     -20504],    16;0
 mov ebx,DWORD  [   labelff69d6e5008+     -20508];0
 fild DWORD  [   labelff69d6e5008+     -20504];2
 floadlit 129.0;2
 fdivp st1;2
 floadlit -1.0;2
 faddp st1;2
 floadlit -1.0;2
 fcom st0,st1  ;2
push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jnb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 1.0;2
 fcom st0,st1  ;2
 push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 127.5;2
 fmulp st1;2
 floadlit -0.5;2
 faddp st1;2
  frndint;2
 sub esp,4;0
 fistp dword [esp];2
 pop  eax;0
 mov dword[fttemp], eax;0
 fild dword[fttemp];2
 sub esp,4;0
 fistp dword [esp];2
 pop  edx;0
 mov BYTE  [  esi+ebx +  labelff69d6e5008+     -20496],dl;0
 inc DWORD  [   labelff69d6e5008+     -20508];0
 imul esi,DWORD  [   labelff69d6e5008+     -20504],    16;0
 mov ebx,DWORD  [   labelff69d6e5008+     -20508];0
 fild DWORD  [   labelff69d6e5008+     -20504];2
 floadlit 129.0;2
 fdivp st1;2
 floadlit -1.0;2
 faddp st1;2
 floadlit -1.0;2
 fcom st0,st1  ;2
push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jnb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 1.0;2
 fcom st0,st1  ;2
 push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 127.5;2
 fmulp st1;2
 floadlit -0.5;2
 faddp st1;2
  frndint;2
 sub esp,4;0
 fistp dword [esp];2
 pop  edx;0
 mov BYTE  [  esi+ebx +  labelff69d6e5008+     -20496],dl;0
 inc DWORD  [   labelff69d6e5008+     -20508];0
 imul esi,DWORD  [   labelff69d6e5008+     -20504],    16;0
 mov ebx,DWORD  [   labelff69d6e5008+     -20508];0
 fild DWORD  [   labelff69d6e5008+     -20504];2
 floadlit 129.0;2
 fdivp st1;2
 floadlit -1.0;2
 faddp st1;2
 floadlit -1.0;2
 fcom st0,st1  ;2
push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jnb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 1.0;2
 fcom st0,st1  ;2
 push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 127.5;2
 fmulp st1;2
 floadlit -0.5;2
 faddp st1;2
  frndint;2
 sub esp,4;0
 fistp dword [esp];2
 pop  edx;0
 mov BYTE  [  esi+ebx +  labelff69d6e5008+     -20496],dl;0
 inc DWORD  [   labelff69d6e5008+     -20508];0
 imul esi,DWORD  [   labelff69d6e5008+     -20504],    16;0
 mov ebx,DWORD  [   labelff69d6e5008+     -20508];0
 fild DWORD  [   labelff69d6e5008+     -20504];2
 floadlit 129.0;2
 fdivp st1;2
 floadlit -1.0;2
 faddp st1;2
 floadlit -1.0;2
 fcom st0,st1  ;2
push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jnb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 1.0;2
 fcom st0,st1  ;2
 push ax;0
 fstsw ax;2
 sahf;0
 pop ax;0
 jb $+4 ;0
 fxch ;2
fstp st1;2
 floadlit 127.5;2
 fmulp st1;2
 floadlit -0.5;2
 faddp st1;2
  frndint;2
 sub esp,4;0
 fistp dword [esp];2
 pop  edx;0
 mov BYTE  [  esi+ebx +  labelff69d6e5008+     -20496],dl;0
 inc DWORD  [   labelff69d6e5008+     -20508];0
 jmp  labelff69d6eef034;0
 labelff69d6eef036:;0
 inc DWORD  [   labelff69d6e5008+     -20504];0
 jmp  labelff69d6eee630;0
 labelff69d6eee632:;0
; #47;0
 mov DWORD  [   labelff69d6e5008+     -20520],     0;0
 labelff69d6f49c38:;0
  cmp DWORD  [   labelff69d6e5008+     -20520],      255;0
 jg near  labelff69d6f49c3a;0
 mov DWORD  [   labelff69d6e5008+     -20524],     0;0
 labelff69d6f4a63c:;0
  cmp DWORD  [   labelff69d6e5008+     -20524],      15;0
 jg near  labelff69d6f4a63e;0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [   labelff69d6e5008+     -20524];0
 imul esi,DWORD  [   labelff69d6e5008+     -20520],    64;0
 imul ebx,DWORD  [   labelff69d6e5008+     -20520],    16;0
 movsx ebx,BYTE    [  ebx+eax +  labelff69d6e5008+     -20496];0
 mov dword[fttemp], ebx;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  esi+ eax* 4+  labelff69d6e5008+     -16384];2
 inc DWORD  [   labelff69d6e5008+     -20524];0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [   labelff69d6e5008+     -20524];0
 imul esi,DWORD  [   labelff69d6e5008+     -20520],    64;0
 imul ebx,DWORD  [   labelff69d6e5008+     -20520],    16;0
 movsx ebx,BYTE    [  ebx+eax +  labelff69d6e5008+     -20496];0
 mov dword[fttemp], ebx;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  esi+ eax* 4+  labelff69d6e5008+     -16384];2
 inc DWORD  [   labelff69d6e5008+     -20524];0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [   labelff69d6e5008+     -20524];0
 imul esi,DWORD  [   labelff69d6e5008+     -20520],    64;0
 imul ebx,DWORD  [   labelff69d6e5008+     -20520],    16;0
 movsx ebx,BYTE    [  ebx+eax +  labelff69d6e5008+     -20496];0
 mov dword[fttemp], ebx;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  esi+ eax* 4+  labelff69d6e5008+     -16384];2
 inc DWORD  [   labelff69d6e5008+     -20524];0
; #substituting in eax with 2 occurences and score of 6;0
 mov eax,DWORD  [   labelff69d6e5008+     -20524];0
 imul esi,DWORD  [   labelff69d6e5008+     -20520],    64;0
 imul ebx,DWORD  [   labelff69d6e5008+     -20520],    16;0
 movsx ebx,BYTE    [  ebx+eax +  labelff69d6e5008+     -20496];0
 mov dword[fttemp], ebx;0
 fild dword[fttemp];2
 floadlit 0.00784313725490196;2
 fmulp st1;2
 floadlit 0.00392156862745098;2
 faddp st1;2
 fstp dword  [  esi+ eax* 4+  labelff69d6e5008+     -16384];2
 inc DWORD  [   labelff69d6e5008+     -20524];0
 jmp  labelff69d6f4a63c;0
 labelff69d6f4a63e:;0
 inc DWORD  [   labelff69d6e5008+     -20520];0
 jmp  labelff69d6f49c38;0
 labelff69d6f49c3a:;0
; #48;0
 labelff69d6ea8412:;0
spaceforunit$vql1 equ 20532;0
unit$vql1exit:;0
leave;0
 ret 0;4
	SECTION .bss;0
	alignb 16;0
resb spaceforunit$vql1;0
	alignb 16;0
 labelff69d6e5008:;0
	SECTION .data;0
unit$vqready dd 0;0
%include "c:\src\VectorPascal\mmpc/system.asm"
%endif
