.ifndef threadlib
 .space 256, ' '
threadlib=1
definedunit$threadlib$base=1
.ifndef definedwait_on_done
definedwait_on_done=1
.extern 	 wait_on_done
.endif
.ifndef definedpost_job
definedpost_job=1
.extern 	 post_job
.endif
.ifndef definedgetframepointer
definedgetframepointer=1
.extern 	 getframepointer
.endif
.section .text  
; #procedure generated by code generator class ilcg.tree.OpteronCG
label122ac50957a26:
#	 unit$threadlib
# entering a unit at lexical level 0
unit$threadlib:
 enter  $0,$0
 call unit$system
cmpb $1,unit$threadlibready
 jnz unit$threadlibinit
 jmp unit$threadlibl0exit
unit$threadlibinit:movb $1, unit$threadlibready
 label122ac50946a24:
spaceforunit$threadlibl0 = 0
unit$threadlibl0exit:
leave
 ret $0
	.section .bss
	.align 16
	.align 16
unit$threadlib$base:
	.section .data
unit$threadlibready: .byte  0
.include "/users/staff/wpc/src/VectorPascal/mmpc/systemOpteron.asm"
.endif
