package VPTeX;

import java.util.*;

class Keywords{

    protected Vector contents;
    Keywords(){
 	contents= new Vector();
	contents.addElement("ABS");
	contents.addElement("ADDR");    
	contents.addElement("AND");
	contents.addElement("ARRAY");
	contents.addElement("BEGIN");
	contents.addElement("BYTE2PIXEL");
	contents.addElement("CASE");
	contents.addElement("CDECL");
	contents.addElement("CHR");
	contents.addElement("CONST");
	contents.addElement("COS");
	contents.addElement("DISPOSE");
	contents.addElement("DIV");
	contents.addElement("DO");
	contents.addElement("DOWNTO");
	contents.addElement("END");
	contents.addElement("ELSE");
	contents.addElement("EXIT");
	contents.addElement("EXTERNAL");
	contents.addElement("FALSE");
	contents.addElement("FILE");
	contents.addElement("FOR");
	contents.addElement("FUNCTION");
	contents.addElement("GOTO");
	contents.addElement("IF");
	contents.addElement("IMPLEMENTATION");
	contents.addElement("IN");
	contents.addElement("INTERFACE");
	contents.addElement("IOTA");
	contents.addElement("LABEL");
	contents.addElement("LIBRARY");
	contents.addElement("LN");
	contents.addElement("MAX");
	contents.addElement("MIN");
	contents.addElement("MOD");
	contents.addElement("NAME");
	contents.addElement("NDX");
	contents.addElement("NEW");
	contents.addElement("NOT");
	contents.addElement("OF");
	contents.addElement("OR");
	contents.addElement("ORD");
	contents.addElement("PACKED");
	contents.addElement("PERM");
	contents.addElement("PIXEL2BYTE");
	contents.addElement("POW");
	contents.addElement("PRED");
	contents.addElement("PROCEDURE");
	contents.addElement("PROGRAM");
	contents.addElement("RDU");
	contents.addElement("READ");
	contents.addElement("READLN");
	contents.addElement("RECORD");
	contents.addElement("REPEAT");
	contents.addElement("ROUND");
	contents.addElement("SET");
	contents.addElement("SHL");
	contents.addElement("SHR");
	contents.addElement("SIN");
	contents.addElement("SIZEOF");
	contents.addElement("STRING");
	contents.addElement("SQRT");
	contents.addElement("SUCC");
	contents.addElement("TAN");
        contents.addElement("THEN");
	contents.addElement("TO"); 
	contents.addElement("TRANS");
	contents.addElement("TRUE"); 
	contents.addElement("TYPE");
	contents.addElement("VAR");
	contents.addElement("WITH");
	contents.addElement("WHILE");
	contents.addElement("WRITE");
	contents.addElement("WRITELN");
	contents.addElement("UNIT");
	contents.addElement("UNTIL"); 
	contents.addElement("USES"); 
    }
}
